name: Forge benchmarks

on:
  workflow_dispatch:
    inputs:
      solx_candidate_branch:
        description: 'Solidity candidate branch to use. If empty, the current branch will be used.'
        required: false
        default: ''
      solx_reference_branch:
        description: 'Solidity reference branch to use. If empty, the current branch will be used.'
        required: false
        default: ''
      compiler_llvm_candidate_branch:
        description: 'LLVM candidate branch to use. If empty, the current branch will be used.'
        required: false
        default: ''
      compiler_llvm_reference_branch:
        description: 'LLVM reference branch to use. If empty, the default repository branch will be used.'
        required: false
        default: 'main'
  pull_request:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.repository_id }}-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  forge-benchmarks:
    uses: matter-labs/era-compiler-ci/.github/workflows/forge-benchmarks.yaml@v1
    secrets: inherit
    with:
      print-markdown-tables: 'false' # do not print markdown tables to PRs
      upload-reports: ${{ github.event_name == 'pull_request' }}
      solx_candidate_branch: ${{ inputs.solx_candidate_branch || 'main' }}
      solx_reference_branch: ${{ inputs.solx_reference_branch || 'main' }}
      compiler_llvm_candidate_branch: ${{ inputs.compiler_llvm_candidate_branch || github.head_ref }}
      compiler_llvm_reference_branch: ${{ inputs.compiler_llvm_reference_branch || github.base_ref || github.event.repository.default_branch }}
      compiler-llvm-repo: ${{ github.event.pull_request.head.repo.full_name || 'matter-labs/era-compiler-llvm' }} # required to properly test forks
