; RUN: llvm-mc -triple eravm -filetype=asm %s -o - | FileCheck %s

  .rodata
foo:
; small signed integers
  .cell -1
  .cell 123

; non-10 radix
  .cell  0b1001
  .cell   01001
  .cell  0x1001
  .cell -0b1001
  .cell  -01001
  .cell -0x1001

; integer between 2^63 and 2^64 should not be printed as if
; it is a negative int64_t value
  .cell 12345678901234567890
; integer that does not fit into uint64_t
  .cell 123456789012345678901234567890

; same as the above, but negative
  .cell -12345678901234567890
  .cell -123456789012345678901234567890

; negation of INT256_MIN
  .cell  0x8000000000000000000000000000000000000000000000000000000000000000
  .cell -0x8000000000000000000000000000000000000000000000000000000000000000


; library address lymbol
.linker_symbol:
  .linker_symbol_cell  @file_sol_Math

; COM: Autogenerated checks below, see README.md.
; CHECK:  .text

; CHECK:  .rodata
; CHECK:foo:
; CHECK:  .cell        -1
; CHECK:  .cell        123

; CHECK:  .cell        9
; CHECK:  .cell        513
; CHECK:  .cell        4097
; CHECK:  .cell        -9
; CHECK:  .cell        -513
; CHECK:  .cell        -4097

; CHECK:  .cell        12345678901234567890
; CHECK:  .cell        123456789012345678901234567890

; CHECK:  .cell        -12345678901234567890
; CHECK:  .cell        -123456789012345678901234567890

; CHECK:  .cell        -57896044618658097711785492504343953926634992332820282019728792003956564819968
; CHECK:  .cell        -57896044618658097711785492504343953926634992332820282019728792003956564819968

; CHECK:.linker_symbol:
; CHECK:  .linker_symbol_cell   @file_sol_Math
