; RUN: llvm-mc -triple eravm -filetype=asm %s -o - | FileCheck %s

  .text
foo:

; mnemonics
  event           r3, r4
  event.first     r3, r4
  to_l1           r3, r4
  to_l1.first     r3, r4

; modifiers (condition)
  event.lt        r3, r4
  event.first.lt  r3, r4
  to_l1.lt        r3, r4
  to_l1.first.lt  r3, r4

; COM: Autogenerated checks below, see README.md.
; CHECK:  .text
; CHECK:foo:

; CHECK:  event        r3, r4
; CHECK:  event.first  r3, r4
; CHECK:  to_l1        r3, r4
; CHECK:  to_l1.first  r3, r4

; CHECK:  event.lt     r3, r4
; CHECK:  event.first.lt       r3, r4
; CHECK:  to_l1.lt     r3, r4
; CHECK:  to_l1.first.lt       r3, r4
