; RUN: llvm-mc -triple eravm -filetype=asm %s -o - | FileCheck %s

  .text
foo:

; modifiers (condition)
  far_call                 r3, r4, @handler
  far_call.delegate             r3, r4, @handler
  far_call.mimic                r3, r4, @handler
  far_call.lt              r3, r4, @handler
  far_call.delegate.lt          r3, r4, @handler
  far_call.mimic.lt             r3, r4, @handler

  far_call.static          r3, r4, @handler
  far_call.delegate.static      r3, r4, @handler
  far_call.mimic.static         r3, r4, @handler
  far_call.static.lt       r3, r4, @handler
  far_call.delegate.static.lt   r3, r4, @handler
  far_call.mimic.static.lt      r3, r4, @handler

  far_call.shard           r3, r4, @handler
  far_call.delegate.shard       r3, r4, @handler
  far_call.mimic.shard          r3, r4, @handler
  far_call.shard.lt        r3, r4, @handler
  far_call.delegate.shard.lt    r3, r4, @handler
  far_call.mimic.shard.lt       r3, r4, @handler

  far_call.static.shard           r3, r4, @handler
  far_call.delegate.static.shard       r3, r4, @handler
  far_call.mimic.static.shard          r3, r4, @handler
  far_call.static.shard.lt        r3, r4, @handler
  far_call.delegate.static.shard.lt    r3, r4, @handler
  far_call.mimic.static.shard.lt       r3, r4, @handler

; COM: Autogenerated checks below, see README.md.
; CHECK:  .text
; CHECK:foo:

; CHECK:  far_call     r3, r4, @handler
; CHECK:  far_call.delegate r3, r4, @handler
; CHECK:  far_call.mimic    r3, r4, @handler
; CHECK:  far_call.lt  r3, r4, @handler
; CHECK:  far_call.delegate.lt      r3, r4, @handler
; CHECK:  far_call.mimic.lt r3, r4, @handler

; CHECK:  far_call.static      r3, r4, @handler
; CHECK:  far_call.delegate.static  r3, r4, @handler
; CHECK:  far_call.mimic.static     r3, r4, @handler
; CHECK:  far_call.static.lt   r3, r4, @handler
; CHECK:  far_call.delegate.static.lt       r3, r4, @handler
; CHECK:  far_call.mimic.static.lt  r3, r4, @handler

; CHECK:  far_call.shard       r3, r4, @handler
; CHECK:  far_call.delegate.shard   r3, r4, @handler
; CHECK:  far_call.mimic.shard      r3, r4, @handler
; CHECK:  far_call.shard.lt    r3, r4, @handler
; CHECK:  far_call.delegate.shard.lt        r3, r4, @handler
; CHECK:  far_call.mimic.shard.lt   r3, r4, @handler

; CHECK:  far_call.static.shard       r3, r4, @handler
; CHECK:  far_call.delegate.static.shard   r3, r4, @handler
; CHECK:  far_call.mimic.static.shard      r3, r4, @handler
; CHECK:  far_call.static.shard.lt    r3, r4, @handler
; CHECK:  far_call.delegate.static.shard.lt        r3, r4, @handler
; CHECK:  far_call.mimic.static.shard.lt   r3, r4, @handler
