; RUN: llvm-mc -triple eravm -filetype=asm %s -o - | FileCheck %s

  .text
foo:

; mnemonics
  ret.ok      r3
  ret.revert  r3
  panic

; modifiers (condition, not testing aliases)
  ret.ok.lt      r3
  ret.revert.lt   r3
  panic.lt

; COM: Autogenerated checks below, see README.md.
; CHECK:  .text
; CHECK:foo:

; CHECK:  ret.ok  r3
; CHECK:  ret.revert       r3
; CHECK:  panic

; CHECK:  ret.ok.lt       r3
; CHECK:  ret.revert.lt    r3
; CHECK:  panic.lt
