; RUN: llvm-mc -triple eravm -filetype=asm %s -o - | FileCheck %s

; FIXME Is there far variant of panic instruction?

  .text
foo:

; mnemonics
  ; FIXME ret         r3
  ret.ok      r3
  ; FIXME revert      r3
  ret.revert  r3
  ; FIXME panic       r3
  ret.panic   r3

; modifiers (condition, not testing aliases)
  ret.ok.lt      r3
  ret.revert.lt   r3
  ret.panic.lt    r3

; COM: Autogenerated checks below, see README.md.
; CHECK:  .text
; CHECK:foo:

; CHECK:  ret.ok  r3
; CHECK:  ret.revert       r3
; CHECK:  ret.panic        r3

; CHECK:  ret.ok.lt       r3
; CHECK:  ret.revert.lt    r3
; CHECK:  ret.panic.lt     r3
