; RUN: llvm-mc -triple eravm -filetype=asm %s -o - | FileCheck %s

  .text
foo:

; mnemonics
  log.decommit  r3, r4, r5
  precompile    r3, r4, r5
  context.this                  r3
  context.caller                r3
  context.code_source           r3
  context.gas_left              r3
  context.sp                    r3
  context.get_context_u128      r3
  context.set_context_u128      r3
  context.meta                  r3
  context.inc_tx_num
  context.set_gas_per_pubdata   r3

; modifiers (condition)
  log.decommit.lt  r3, r4, r5
  precompile.lt    r3, r4, r5
  context.this.lt                  r3
  context.caller.lt                r3
  context.code_source.lt           r3
  context.gas_left.lt              r3
  context.sp.lt                    r3
  context.get_context_u128.lt      r3
  context.set_context_u128.lt      r3
  context.meta.lt                  r3
  context.inc_tx_num.lt
  context.set_gas_per_pubdata.lt   r3


; COM: Autogenerated checks below, see README.md.
; CHECK:  .text
; CHECK:foo:

; CHECK:  log.decommit  r3, r4, r5
; CHECK:  precompile    r3, r4, r5
; CHECK:  context.this r3
; CHECK:  context.caller       r3
; CHECK:  context.code_source  r3
; CHECK:  context.gas_left     r3
; CHECK:  context.sp   r3
; CHECK:  context.get_context_u128     r3
; CHECK:  context.set_context_u128     r3
; CHECK:  context.meta r3
; CHECK:  context.inc_tx_num
; CHECK:  context.set_gas_per_pubdata  r3

; CHECK:  log.decommit.lt      r3, r4, r5
; CHECK:  precompile.lt        r3, r4, r5
; CHECK:  context.this.lt      r3
; CHECK:  context.caller.lt    r3
; CHECK:  context.code_source.lt       r3
; CHECK:  context.gas_left.lt  r3
; CHECK:  context.sp.lt        r3
; CHECK:  context.get_context_u128.lt  r3
; CHECK:  context.set_context_u128.lt  r3
; CHECK:  context.meta.lt      r3
; CHECK:  context.inc_tx_num.lt
; CHECK:  context.set_gas_per_pubdata.lt       r3
