; RUN: llvm-mc -triple eravm -filetype=asm %s -o - | FileCheck %s

  .text
foo:

; mnemonics
  dcmt      r3, r4, r5
  callp     r3, r4, r5
  this      r3
  par       r3
  code      r3
  ergs      r3
  sp        r3
  ldvl      r3
  stvl      r3
  meta      r3
  inctx
  stpub     r3  ; removed in VM 1.5.0

; modifiers (condition)
  dcmt.lt   r3, r4, r5
  callp.lt  r3, r4, r5
  this.lt   r3
  par.lt    r3
  code.lt   r3
  ergs.lt   r3
  sp.lt     r3
  ldvl.lt   r3
  stvl.lt   r3
  meta.lt   r3
  inctx.lt
  stpub.lt  r3  ; removed in VM 1.5.0


; COM: Autogenerated checks below, see README.md.
; CHECK:  .text
; CHECK:foo:

; CHECK:  dcmt      r3, r4, r5
; CHECK:  callp     r3, r4, r5
; CHECK:  this      r3
; CHECK:  par       r3
; CHECK:  code      r3
; CHECK:  ergs      r3
; CHECK:  sp        r3
; CHECK:  ldvl      r3
; CHECK:  stvl      r3
; CHECK:  meta      r3
; CHECK:  inctx
; CHECK:  stpub     r3

; CHECK:  dcmt.lt   r3, r4, r5
; CHECK:  callp.lt  r3, r4, r5
; CHECK:  this.lt   r3
; CHECK:  par.lt    r3
; CHECK:  code.lt   r3
; CHECK:  ergs.lt   r3
; CHECK:  sp.lt     r3
; CHECK:  ldvl.lt   r3
; CHECK:  stvl.lt   r3
; CHECK:  meta.lt   r3
; CHECK:  inctx.lt
; CHECK:  stpub.lt  r3
