; RUN: llvm-mc -triple eravm -filetype=asm %s -o - | FileCheck %s

  .text
foo:

; modifiers (condition)
  jump       r1
  jump.lt    r1

; 5 src modes
  jump       r1
  jump       @label
  jump       stack[r1 + 1]
  jump       stack-[r1 + 1]
  jump       code[r1 + 1]

; do not confuse @jump_target and @indirect_via_const[1]
  jump       @label
  jump       @jump_table[1]

; COM: Autogenerated checks below, see README.md.
; CHECK:  .text
; CHECK:foo:

; CHECK:  jump r1
; CHECK:  jump.lt      r1

; CHECK:  jump r1
; CHECK:  jump @label
; CHECK:  jump stack[1 + r1]
; CHECK:  jump stack-[1 + r1]
; CHECK:  jump code[r1+1]

; CHECK:  jump @label
; CHECK:  jump @jump_table[r0+1]
