; RUN: llvm-mc -triple eravm -filetype=asm %s -o - | FileCheck %s

  .text
foo:

; 3-operand form
  near_call      r3, @callee, @exception_handler
; 2-operand form
  near_call      r3, @callee
; 1-operand form
  near_call      @callee

; modifiers (condition)
  near_call.lt   r3, @callee, @exception_handler
  near_call.lt   r3, @callee
  near_call.lt   @callee


; COM: Autogenerated checks below, see README.md.
; CHECK:  .text
; CHECK:foo:

; CHECK:  near_call    r3, @callee, @exception_handler
; CHECK:  near_call    r3, @callee
; CHECK:  near_call    @callee

; CHECK:  near_call.lt r3, @callee, @exception_handler
; CHECK:  near_call.lt r3, @callee
; CHECK:  near_call.lt @callee
