; RUN: llvm-mc -triple eravm -filetype=asm %s -o - | FileCheck %s

  .text
foo:

; modifiers (condition)
  jump       r1
  jump.lt    r1
  jump       r1, r2
  jump.lt    r1, r2

; 6 src modes
  jump       r1
  jump       @label
  jump       stack[r1 + 1]
  jump       stack-[r1 + 1]
  jump       stack-=[r1 + 1]
  jump       code[r1 + 1]
; 6 src modes (with return address operand)
  jump       r1, r2
  jump       @label, r2
  jump       stack[r1 + 1], r2
  jump       stack-[r1 + 1], r2
  jump       stack-=[r1 + 1], r2
  jump       code[r1 + 1], r2

; do not confuse @jump_target and @indirect_via_const[1]
  jump       @label
  jump       @jump_table[1]
  jump       @label, r2
  jump       @jump_table[1], r2

; COM: Autogenerated checks below, see README.md.
; CHECK:  .text
; CHECK:foo:

; CHECK:  jump r1
; CHECK:  jump.lt      r1
; CHECK:  jump r1, r2
; CHECK:  jump.lt      r1, r2

; CHECK:  jump r1
; CHECK:  jump @label
; CHECK:  jump stack[1 + r1]
; CHECK:  jump stack-[1 + r1]
; CHECK:  jump stack-=[1 + r1]
; CHECK:  jump code[r1+1]
; CHECK:  jump r1, r2
; CHECK:  jump @label, r2
; CHECK:  jump stack[1 + r1], r2
; CHECK:  jump stack-[1 + r1], r2
; CHECK:  jump stack-=[1 + r1], r2
; CHECK:  jump code[r1+1], r2

; CHECK:  jump @label
; CHECK:  jump @jump_table[1]
; CHECK:  jump @label, r2
; CHECK:  jump @jump_table[1], r2
