; RUN: llvm-mc -triple eravm -filetype=asm %s -o - | FileCheck %s

  .text
foo:

; mnemonics
  ret        ; aliased to ret r1
  ret r1
  ret r3
  rev        ; aliased to rev r1
  rev r1
  rev r3
  pnc
  retl @label
  revl @label
  pncl @label

; modifiers (condition)
  ret.lt
  rev.lt
  ret.lt r3
  rev.lt r3
  pnc.lt
  retl.lt @label
  revl.lt @label
  pncl.lt @label

; aliases
  retl      r1, @label
  revl      r1, @label
  retl.lt   r1, @label
  revl.lt   r1, @label
; generic case
  retl      r3, @label
  revl      r3, @label
  retl.lt   r3, @label
  revl.lt   r3, @label

; COM: Autogenerated checks below, see README.md.
; CHECK:  .text
; CHECK:foo:

; CHECK:  ret
; CHECK:  ret
; CHECK:  ret r3
; CHECK:  rev
; CHECK:  rev
; CHECK:  rev r3
; CHECK:  pnc
; CHECK:  retl  @label
; CHECK:  revl  @label
; CHECK:  pncl  @label

; CHECK:  ret.lt
; CHECK:  rev.lt
; CHECK:  ret.lt r3
; CHECK:  rev.lt r3
; CHECK:  pnc.lt
; CHECK:  retl.lt @label
; CHECK:  revl.lt @label
; CHECK:  pncl.lt @label

; CHECK:  retl       @label
; CHECK:  revl       @label
; CHECK:  retl.lt    @label
; CHECK:  revl.lt    @label
; CHECK:  retl       r3, @label
; CHECK:  revl       r3, @label
; CHECK:  retl.lt    r3, @label
; CHECK:  revl.lt    r3, @label
