; RUN: llvm-mc -triple eravm -filetype=asm %s -o - | FileCheck %s

  .text
foo:

; mnemonics
  lds       r3, r4
  sts       r3, r4
  ldt       r3, r4
  stt       r3, r4

; modifiers (condition)
  lds.lt    r3, r4
  sts.lt    r3, r4
  ldt.lt    r3, r4
  stt.lt    r3, r4

; COM: Autogenerated checks below, see README.md.
; CHECK:  .text
; CHECK:foo:

; CHECK:  lds       r3, r4
; CHECK:  sts       r3, r4
; CHECK:  ldt       r3, r4
; CHECK:  stt       r3, r4

; CHECK:  lds.lt    r3, r4
; CHECK:  sts.lt    r3, r4
; CHECK:  ldt.lt    r3, r4
; CHECK:  stt.lt    r3, r4
