; RUN: llvm-mc -triple eravm -filetype=asm %s -o - | FileCheck %s

  .text
foo:

; mnemonics
  sload       r3, r4
  sstore      r3, r4
  log.sread   r3, r4 ; aliased to "sload  r3, r4"
  log.swrite  r3, r4 ; aliased to "sstore r3, r4"

; modifiers (condition)
  sload.lt    r3, r4
  sstore.lt   r3, r4

; COM: Autogenerated checks below, see README.md.
; CHECK:  .text
; CHECK:foo:

; CHECK:  sload        r3, r4
; CHECK:  sstore       r3, r4
; CHECK:  sload        r3, r4
; CHECK:  sstore       r3, r4

; CHECK:  sload.lt     r3, r4
; CHECK:  sstore.lt    r3, r4
