; RUN: llvm-mc -triple eravm -filetype=asm %s -o - | FileCheck %s

  .text
foo:

; mnemonics
  ldp       r3, r4
  ldpi      r3, r4, r5

  ldm.h     r3, r4
  ldm.ah    r3, r4
  ldmi.h    r3, r4, r5
  ldmi.ah   r3, r4, r5

  stm.h     r3, r4
  stm.ah    r3, r4
  stmi.h    r3, r4, r5
  stmi.ah   r3, r4, r5

  ldm.st    r3, r4
  ldmi.st   r3, r4, r5
  stm.st    r3, r4
  stmi.st   r3, r4, r5

; modifiers (condition code)

  ldp.lt        r3, r4
  ldpi.lt       r3, r4, r5
  ldm.h.lt      r3, r4
  ldm.ah.lt     r3, r4
  ldmi.h.lt     r3, r4, r5
  ldmi.ah.lt    r3, r4, r5
  stm.h.lt      r3, r4
  stm.ah.lt     r3, r4
  stmi.h.lt     r3, r4, r5
  stmi.ah.lt    r3, r4, r5
  ldm.st.lt     r3, r4
  ldmi.st.lt    r3, r4, r5
  stm.st.lt     r3, r4
  stmi.st.lt    r3, r4, r5

; operands (instructions operating on "local" heap can accept immediate addresses)
  ldm.h     42, r4
  ldm.ah    42, r4
  ldmi.h    42, r4, r5
  ldmi.ah   42, r4, r5
  stm.h     42, r4
  stm.ah    42, r4
  stmi.h    42, r4, r5
  stmi.ah   42, r4, r5
  ldm.st    42, r4
  ldmi.st   42, r4, r5
  stm.st    42, r4
  stmi.st   42, r4, r5

; COM: Autogenerated checks below, see README.md.
; CHECK:  .text
; CHECK:foo:

; CHECK:  ldp       r3, r4
; CHECK:  ldpi      r3, r4, r5

; CHECK:  ldm.h     r3, r4
; CHECK:  ldm.ah    r3, r4
; CHECK:  ldmi.h    r3, r4, r5
; CHECK:  ldmi.ah   r3, r4, r5

; CHECK:  stm.h     r3, r4
; CHECK:  stm.ah    r3, r4
; CHECK:  stmi.h    r3, r4, r5
; CHECK:  stmi.ah   r3, r4, r5

; CHECK:  ldm.st    r3, r4
; CHECK:  ldmi.st   r3, r4, r5
; CHECK:  stm.st    r3, r4
; CHECK:  stmi.st   r3, r4, r5

; CHECK:  ldp.lt        r3, r4
; CHECK:  ldpi.lt       r3, r4, r5
; CHECK:  ldm.h.lt      r3, r4
; CHECK:  ldm.ah.lt     r3, r4
; CHECK:  ldmi.h.lt     r3, r4, r5
; CHECK:  ldmi.ah.lt    r3, r4, r5
; CHECK:  stm.h.lt      r3, r4
; CHECK:  stm.ah.lt     r3, r4
; CHECK:  stmi.h.lt     r3, r4, r5
; CHECK:  stmi.ah.lt    r3, r4, r5
; CHECK:  ldm.st.lt     r3, r4
; CHECK:  ldmi.st.lt    r3, r4, r5
; CHECK:  stm.st.lt     r3, r4
; CHECK:  stmi.st.lt    r3, r4, r5

; CHECK:  ldm.h     42, r4
; CHECK:  ldm.ah    42, r4
; CHECK:  ldmi.h    42, r4, r5
; CHECK:  ldmi.ah   42, r4, r5
; CHECK:  stm.h     42, r4
; CHECK:  stm.ah    42, r4
; CHECK:  stmi.h    42, r4, r5
; CHECK:  stmi.ah   42, r4, r5
; CHECK:  ldm.st    42, r4
; CHECK:  ldmi.st   42, r4, r5
; CHECK:  stm.st    42, r4
; CHECK:  stmi.st   42, r4, r5
