; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S32-a:256:256"
target triple = "eravm"

; TODO: optimize

define i256 @brcond(i256 %p1) nounwind {
; CHECK-LABEL: brcond:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    and 1, r1, r1
; CHECK-NEXT:    add 0, r0, r2
; CHECK-NEXT:    sub! r1, r2, r1
; CHECK-NEXT:    jump.eq @.BB0_2
; CHECK-NEXT:  ; %bb.1: ; %l1
; CHECK-NEXT:    add 42, r0, r1
; CHECK-NEXT:    ret
; CHECK-NEXT:  .BB0_2: ; %l2
; CHECK-NEXT:    add 43, r0, r1
; CHECK-NEXT:    ret
  %1 = trunc i256 %p1 to i1
  br i1 %1, label %l1, label %l2
l1:
  ret i256 42
l2:
  ret i256 43
}
