; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -O3 < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S32-a:256:256"
target triple = "eravm"

@val = addrspace(4) global i256 42

define i256 @test_large_imm_no_fold1(i256 %a, i1 %cond) {
; CHECK-LABEL: test_large_imm_no_fold1:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub.s code[@CPI0_0], r1, r3
; CHECK-NEXT:    sub.s! code[@CPI0_1], r1, r0
; CHECK-NEXT:    add.lt r3, r0, r1
; CHECK-NEXT:    sub! r2, r0, r0
; CHECK-NEXT:    add.eq r3, r0, r1
; CHECK-NEXT:    ret
  %add = add i256 %a, 26959946660873538059280334323183841250350249843923952699046031785980
  %cmp = icmp ult i256 %a, -26959946660873538059280334323183841250350249843923952699046031785985
  %select1 = select i1 %cmp, i256 %add, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %add
  ret i256 %select2
}

define i256 @test_large_imm_no_fold2(i256 %a, i1 %cond) {
; CHECK-LABEL: test_large_imm_no_fold2:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub.s code[@CPI1_0], r1, r3
; CHECK-NEXT:    sub.s! code[@CPI1_1], r1, r0
; CHECK-NEXT:    add.lt r3, r0, r1
; CHECK-NEXT:    sub! r2, r0, r0
; CHECK-NEXT:    add.eq r3, r0, r1
; CHECK-NEXT:    ret
  %add = add i256 %a, -26959946660873538059280334323183841250350249843923952699046031785980
  %cmp = icmp ult i256 %a, 26959946660873538059280334323183841250350249843923952699046031785985
  %select1 = select i1 %cmp, i256 %add, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %add
  ret i256 %select2
}

define i256 @test_small_imm_no_fold(i256 %a, i1 %cond) {
; CHECK-LABEL: test_small_imm_no_fold:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub.s 5, r1, r3
; CHECK-NEXT:    sub.s! 10, r1, r0
; CHECK-NEXT:    add.lt r3, r0, r1
; CHECK-NEXT:    sub! r2, r0, r0
; CHECK-NEXT:    add.eq r3, r0, r1
; CHECK-NEXT:    ret
  %add = add i256 %a, -5
  %cmp = icmp ult i256 %a, 10
  %select1 = select i1 %cmp, i256 %add, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %add
  ret i256 %select2
}

define i256 @test_large_imm_ult1(i256 %a, i1 %cond) {
; CHECK-LABEL: test_large_imm_ult1:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub.s! code[@CPI3_0], r1, r3
; CHECK-NEXT:    add.lt r3, r0, r1
; CHECK-NEXT:    sub! r2, r0, r0
; CHECK-NEXT:    add.eq r3, r0, r1
; CHECK-NEXT:    ret
  %add = add i256 %a, 26959946660873538059280334323183841250350249843923952699046031785985
  %cmp = icmp ult i256 %a, -26959946660873538059280334323183841250350249843923952699046031785985
  %select1 = select i1 %cmp, i256 %add, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %add
  ret i256 %select2
}

define i256 @test_large_imm_ult2(i256 %a, i1 %cond) {
; CHECK-LABEL: test_large_imm_ult2:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub.s! code[@CPI4_0], r1, r3
; CHECK-NEXT:    add.lt r3, r0, r1
; CHECK-NEXT:    sub! r2, r0, r0
; CHECK-NEXT:    add.eq r3, r0, r1
; CHECK-NEXT:    ret
  %add = add i256 %a, -26959946660873538059280334323183841250350249843923952699046031785985
  %cmp = icmp ult i256 %a, 26959946660873538059280334323183841250350249843923952699046031785985
  %select1 = select i1 %cmp, i256 %add, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %add
  ret i256 %select2
}

define i256 @test_large_imm_ule1(i256 %a, i1 %cond) {
; CHECK-LABEL: test_large_imm_ule1:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub.s! code[@CPI5_0], r1, r3
; CHECK-NEXT:    add.le r3, r0, r1
; CHECK-NEXT:    sub! r2, r0, r0
; CHECK-NEXT:    add.eq r3, r0, r1
; CHECK-NEXT:    ret
  %add = add i256 %a, 26959946660873538059280334323183841250350249843923952699046031785985
  %cmp = icmp ule i256 %a, -26959946660873538059280334323183841250350249843923952699046031785985
  %select1 = select i1 %cmp, i256 %add, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %add
  ret i256 %select2
}

define i256 @test_large_imm_ule2(i256 %a, i1 %cond) {
; CHECK-LABEL: test_large_imm_ule2:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub.s! code[@CPI6_0], r1, r3
; CHECK-NEXT:    add.le r3, r0, r1
; CHECK-NEXT:    sub! r2, r0, r0
; CHECK-NEXT:    add.eq r3, r0, r1
; CHECK-NEXT:    ret
  %add = add i256 %a, -26959946660873538059280334323183841250350249843923952699046031785985
  %cmp = icmp ule i256 %a, 26959946660873538059280334323183841250350249843923952699046031785985
  %select1 = select i1 %cmp, i256 %add, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %add
  ret i256 %select2
}

; TODO #654: This can be folded.
define i256 @test_small_large_imm_ule(i256 %a, i1 %cond) {
; CHECK-LABEL: test_small_large_imm_ule:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub.s 65535, r1, r3
; CHECK-NEXT:    sub.s! code[@CPI7_0], r1, r0
; CHECK-NEXT:    add.lt r3, r0, r1
; CHECK-NEXT:    sub! r2, r0, r0
; CHECK-NEXT:    add.eq r3, r0, r1
; CHECK-NEXT:    ret
  %add = add i256 %a, -65535
  %cmp = icmp ule i256 %a, 65535
  %select1 = select i1 %cmp, i256 %add, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %add
  ret i256 %select2
}

define i256 @test_large_imm_uge1(i256 %a, i1 %cond) {
; CHECK-LABEL: test_large_imm_uge1:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub.s! code[@CPI8_0], r1, r3
; CHECK-NEXT:    add.ge r3, r0, r1
; CHECK-NEXT:    sub! r2, r0, r0
; CHECK-NEXT:    add.eq r3, r0, r1
; CHECK-NEXT:    ret
  %add = add i256 %a, 26959946660873538059280334323183841250350249843923952699046031785985
  %cmp = icmp uge i256 %a, -26959946660873538059280334323183841250350249843923952699046031785985
  %select1 = select i1 %cmp, i256 %add, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %add
  ret i256 %select2
}

define i256 @test_large_imm_uge2(i256 %a, i1 %cond) {
; CHECK-LABEL: test_large_imm_uge2:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub.s! code[@CPI9_0], r1, r3
; CHECK-NEXT:    add.ge r3, r0, r1
; CHECK-NEXT:    sub! r2, r0, r0
; CHECK-NEXT:    add.eq r3, r0, r1
; CHECK-NEXT:    ret
  %add = add i256 %a, -26959946660873538059280334323183841250350249843923952699046031785985
  %cmp = icmp uge i256 %a, 26959946660873538059280334323183841250350249843923952699046031785985
  %select1 = select i1 %cmp, i256 %add, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %add
  ret i256 %select2
}

; TODO #654: This can be folded.
define i256 @test_small_large_imm_uge(i256 %a, i1 %cond) {
; CHECK-LABEL: test_small_large_imm_uge:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub.s code[@CPI10_0], r1, r3
; CHECK-NEXT:    sub.s! 65535, r1, r0
; CHECK-NEXT:    add.gt r3, r0, r1
; CHECK-NEXT:    sub! r2, r0, r0
; CHECK-NEXT:    add.eq r3, r0, r1
; CHECK-NEXT:    ret
  %add = add i256 %a, -65536
  %cmp = icmp uge i256 %a, 65536
  %select1 = select i1 %cmp, i256 %add, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %add
  ret i256 %select2
}

define i256 @test_small_imm_ult(i256 %a, i1 %cond) {
; CHECK-LABEL: test_small_imm_ult:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub.s! 5, r1, r3
; CHECK-NEXT:    add.lt r3, r0, r1
; CHECK-NEXT:    sub! r2, r0, r0
; CHECK-NEXT:    add.eq r3, r0, r1
; CHECK-NEXT:    ret
  %add = add i256 %a, -5
  %cmp = icmp ult i256 %a, 5
  %select1 = select i1 %cmp, i256 %add, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %add
  ret i256 %select2
}

define i256 @test_small_imm_ule(i256 %a, i1 %cond) {
; CHECK-LABEL: test_small_imm_ule:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub.s! 5, r1, r3
; CHECK-NEXT:    add.le r3, r0, r1
; CHECK-NEXT:    sub! r2, r0, r0
; CHECK-NEXT:    add.eq r3, r0, r1
; CHECK-NEXT:    ret
  %add = add i256 %a, -5
  %cmp = icmp ule i256 %a, 5
  %select1 = select i1 %cmp, i256 %add, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %add
  ret i256 %select2
}

define i256 @test_small_imm_uge(i256 %a, i1 %cond) {
; CHECK-LABEL: test_small_imm_uge:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub.s! 5, r1, r3
; CHECK-NEXT:    add.ge r3, r0, r1
; CHECK-NEXT:    sub! r2, r0, r0
; CHECK-NEXT:    add.eq r3, r0, r1
; CHECK-NEXT:    ret
  %add = add i256 %a, -5
  %cmp = icmp uge i256 %a, 5
  %select1 = select i1 %cmp, i256 %add, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %add
  ret i256 %select2
}

define i256 @test_reg1(i256 %a, i256 %b, i1 %cond) {
; CHECK-LABEL: test_reg1:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r2, r2
; CHECK-NEXT:    add.lt r2, r0, r1
; CHECK-NEXT:    sub! r3, r0, r0
; CHECK-NEXT:    add.eq r2, r0, r1
; CHECK-NEXT:    ret
  %sub = sub i256 %a, %b
  %cmp = icmp ult i256 %a, %b
  %select1 = select i1 %cmp, i256 %sub, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %sub
  ret i256 %select2
}

define i256 @test_reg2(i256 %a, i256 %b, i1 %cond) {
; CHECK-LABEL: test_reg2:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r2, r1, r2
; CHECK-NEXT:    add.lt r2, r0, r1
; CHECK-NEXT:    sub! r3, r0, r0
; CHECK-NEXT:    add.eq r2, r0, r1
; CHECK-NEXT:    ret
  %sub = sub i256 %b, %a
  %cmp = icmp ult i256 %b, %a
  %select1 = select i1 %cmp, i256 %sub, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %sub
  ret i256 %select2
}

define i256 @test_stack1(i256 %a, i1 %cond) {
; CHECK-LABEL: test_stack1:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    incsp 1
; CHECK-NEXT:    sub.s! stack-[1], r1, r3
; CHECK-NEXT:    add.lt r3, r0, r1
; CHECK-NEXT:    sub! r2, r0, r0
; CHECK-NEXT:    add.eq r3, r0, r1
; CHECK-NEXT:    ret
  %bptr = alloca i256
  %b = load i256, i256* %bptr
  %sub = sub i256 %a, %b
  %cmp = icmp ult i256 %a, %b
  %select1 = select i1 %cmp, i256 %sub, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %sub
  ret i256 %select2
}

define i256 @test_stack2(i256 %a, i1 %cond) {
; CHECK-LABEL: test_stack2:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    incsp 1
; CHECK-NEXT:    sub! stack-[1], r1, r3
; CHECK-NEXT:    add.lt r3, r0, r1
; CHECK-NEXT:    sub! r2, r0, r0
; CHECK-NEXT:    add.eq r3, r0, r1
; CHECK-NEXT:    ret
  %bptr = alloca i256
  %b = load i256, i256* %bptr
  %sub = sub i256 %b, %a
  %cmp = icmp ult i256 %b, %a
  %select1 = select i1 %cmp, i256 %sub, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %sub
  ret i256 %select2
}

define i256 @test_code1(i256 %a, i1 %cond) {
; CHECK-LABEL: test_code1:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub.s! code[@val], r1, r3
; CHECK-NEXT:    add.lt r3, r0, r1
; CHECK-NEXT:    sub! r2, r0, r0
; CHECK-NEXT:    add.eq r3, r0, r1
; CHECK-NEXT:    ret
  %b = load i256, i256 addrspace(4)* @val
  %sub = sub i256 %a, %b
  %cmp = icmp ult i256 %a, %b
  %select1 = select i1 %cmp, i256 %sub, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %sub
  ret i256 %select2
}

define i256 @test_code2(i256 %a, i1 %cond) {
; CHECK-LABEL: test_code2:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! code[@val], r1, r3
; CHECK-NEXT:    add.lt r3, r0, r1
; CHECK-NEXT:    sub! r2, r0, r0
; CHECK-NEXT:    add.eq r3, r0, r1
; CHECK-NEXT:    ret
  %b = load i256, i256 addrspace(4)* @val
  %sub = sub i256 %b, %a
  %cmp = icmp ult i256 %b, %a
  %select1 = select i1 %cmp, i256 %sub, i256 %a
  %select2 = select i1 %cond, i256 %select1, i256 %sub
  ret i256 %select2
}
