; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -O3 --disable-eravm-scalar-opt-passes < %s | FileCheck %s
target datalayout = "E-p:256:256-i256:256:256-S32-a:256:256"
target triple = "eravm"

define void @loop1(i256 addrspace(1)* %dest, i256 addrspace(1)* %src, i256 %size) {
; CHECK-LABEL: loop1:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub.s! 1, r3, r0
; CHECK-NEXT:    add.le 1, r0, r3
; CHECK-NEXT:    shl.s 5, r3, r3
; CHECK-NEXT:    add r1, r3, r3
; CHECK-NEXT:  .BB0_1: ; %load-store-loop
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldmi.h r2, r4, r2
; CHECK-NEXT:    stmi.h r1, r4, r1
; CHECK-NEXT:    sub! r1, r3, r0
; CHECK-NEXT:    jump.ne @.BB0_1
; CHECK-NEXT:  ; %bb.2: ; %memcpy-split
; CHECK-NEXT:    ret

  br label %load-store-loop

load-store-loop:                                  ; preds = %load-store-loop, %0
  %loop-index = phi i256 [ 0, %0 ], [ %4, %load-store-loop ]
  %1 = getelementptr inbounds i256, i256 addrspace(1)* %src, i256 %loop-index
  %2 = load i256, i256 addrspace(1)* %1, align 1
  %3 = getelementptr inbounds i256, i256 addrspace(1)* %dest, i256 %loop-index
  store i256 %2, i256 addrspace(1)* %3, align 1
  %4 = add i256 %loop-index, 1
  %5 = icmp ult i256 %4, %size
  br i1 %5, label %load-store-loop, label %memcpy-split

memcpy-split:                                     ; preds = %load-store-loop
  ret void
}

define void @loop2(i256 addrspace(1)* %dest, i256 addrspace(1)* %src, i256 %size) {
; CHECK-LABEL: loop2:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    sub.s! 11, r3, r0
; CHECK-NEXT:    add.le 11, r0, r3
; CHECK-NEXT:    shl.s 5, r3, r3
; CHECK-NEXT:    add r1, r3, r3
; CHECK-NEXT:    add 320, r1, r1
; CHECK-NEXT:    add 320, r2, r2
; CHECK-NEXT:  .BB1_1: ; %load-store-loop
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldmi.h r2, r4, r2
; CHECK-NEXT:    stmi.h r1, r4, r1
; CHECK-NEXT:    sub! r1, r3, r0
; CHECK-NEXT:    jump.ne @.BB1_1
; CHECK-NEXT:  ; %bb.2: ; %memcpy-split
; CHECK-NEXT:    ret

entry:
  br label %load-store-loop

load-store-loop:                                  ; preds = %load-store-loop, %entry
  %loop-index = phi i256 [ 10, %entry ], [ %3, %load-store-loop ]
  %0 = getelementptr inbounds i256, i256 addrspace(1)* %src, i256 %loop-index
  %1 = load i256, i256 addrspace(1)* %0, align 1
  %2 = getelementptr inbounds i256, i256 addrspace(1)* %dest, i256 %loop-index
  store i256 %1, i256 addrspace(1)* %2, align 1
  %3 = add i256 %loop-index, 1
  %4 = icmp ult i256 %3, %size
  br i1 %4, label %load-store-loop, label %memcpy-split

memcpy-split:                                     ; preds = %load-store-loop
  ret void
}

define void @loop3(i256 addrspace(1)* %dest, i256 addrspace(1)* %src, i256 %size, i256 %pos) {
; CHECK-LABEL: loop3:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    shl.s 5, r4, r4
; CHECK-NEXT:    add r4, r2, r4
; CHECK-NEXT:    add 10, r0, r2
; CHECK-NEXT:    add 32, r4, r4
; CHECK-NEXT:  .BB2_1: ; %load-store-loop
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    shl.s 5, r2, r5
; CHECK-NEXT:    add r1, r5, r5
; CHECK-NEXT:    ldmi.h r4, r6, r4
; CHECK-NEXT:    stm.h r5, r6
; CHECK-NEXT:    add 2, r2, r2
; CHECK-NEXT:    sub! r2, r3, r0
; CHECK-NEXT:    jump.lt @.BB2_1
; CHECK-NEXT:  ; %bb.2: ; %memcpy-split
; CHECK-NEXT:    ret

entry:
  %src-index-init = add i256 %pos, 1
  br label %load-store-loop

load-store-loop:                                  ; preds = %load-store-loop, %entry
  %loop-index = phi i256 [ 10, %entry ], [ %3, %load-store-loop ]
  %src-index = phi i256 [ %src-index-init, %entry ], [ %src-index-inc, %load-store-loop ]
  %0 = getelementptr inbounds i256, i256 addrspace(1)* %src, i256 %src-index
  %1 = load i256, i256 addrspace(1)* %0, align 1
  %2 = getelementptr inbounds i256, i256 addrspace(1)* %dest, i256 %loop-index
  store i256 %1, i256 addrspace(1)* %2, align 1
  %src-index-inc = add i256 %src-index, 1
  %3 = add i256 %loop-index, 2
  %4 = icmp ult i256 %3, %size
  br i1 %4, label %load-store-loop, label %memcpy-split

memcpy-split:                                     ; preds = %load-store-loop
  ret void
}

define void @loop4([10 x i256] addrspace(1)* %dest, [10 x i256] addrspace(1)* %src, i256 %size) {
; CHECK-LABEL: loop4:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub.s! 1, r3, r0
; CHECK-NEXT:    add.le 1, r0, r3
; CHECK-NEXT:    shl.s 5, r3, r3
; CHECK-NEXT:    add r1, r3, r3
; CHECK-NEXT:  .BB3_1: ; %load-store-loop
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldmi.h r2, r4, r2
; CHECK-NEXT:    stmi.h r1, r4, r1
; CHECK-NEXT:    sub! r1, r3, r0
; CHECK-NEXT:    jump.ne @.BB3_1
; CHECK-NEXT:  ; %bb.2: ; %memcpy-split
; CHECK-NEXT:    ret
  br label %load-store-loop

load-store-loop:                                  ; preds = %load-store-loop, %0
  %loop-index = phi i256 [ 0, %0 ], [ %4, %load-store-loop ]
  %1 = getelementptr [10 x i256], [10 x i256] addrspace(1)* %src, i256 0, i256 %loop-index
  %2 = load i256, i256 addrspace(1)* %1, align 1
  %3 = getelementptr [10 x i256], [10 x i256] addrspace(1)* %dest, i256 0, i256 %loop-index
  store i256 %2, i256 addrspace(1)* %3, align 1
  %4 = add i256 %loop-index, 1
  %5 = icmp ult i256 %4, %size
  br i1 %5, label %load-store-loop, label %memcpy-split

memcpy-split:                                     ; preds = %load-store-loop
  ret void
}

define void @loop5([10 x i256] addrspace(1)* %dest, [10 x i256] addrspace(1)* %src, i256 %size) {
; CHECK-LABEL: loop5:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    add 320, r1, r1
; CHECK-NEXT:    sub.s! 1, r3, r0
; CHECK-NEXT:    add.le 1, r0, r3
; CHECK-NEXT:    shl.s 5, r3, r3
; CHECK-NEXT:    add r1, r3, r3
; CHECK-NEXT:    add 320, r2, r2
; CHECK-NEXT:  .BB4_1: ; %load-store-loop
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldmi.h r2, r4, r2
; CHECK-NEXT:    stmi.h r1, r4, r1
; CHECK-NEXT:    sub! r1, r3, r0
; CHECK-NEXT:    jump.ne @.BB4_1
; CHECK-NEXT:  ; %bb.2: ; %memcpy-split
; CHECK-NEXT:    ret
  br label %load-store-loop

load-store-loop:                                  ; preds = %load-store-loop, %0
  %loop-index = phi i256 [ 0, %0 ], [ %4, %load-store-loop ]
  %1 = getelementptr [10 x i256], [10 x i256] addrspace(1)* %src, i256 1, i256 %loop-index
  %2 = load i256, i256 addrspace(1)* %1, align 1
  %3 = getelementptr [10 x i256], [10 x i256] addrspace(1)* %dest, i256 1, i256 %loop-index
  store i256 %2, i256 addrspace(1)* %3, align 1
  %4 = add i256 %loop-index, 1
  %5 = icmp ult i256 %4, %size
  br i1 %5, label %load-store-loop, label %memcpy-split

memcpy-split:                                     ; preds = %load-store-loop
  ret void
}

define void @loop6(i256 addrspace(1)* %dest, i256 addrspace(3)* %src, i256 %size) {
; CHECK-LABEL: loop6:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub.s! 1, r3, r0
; CHECK-NEXT:    add.le 1, r0, r3
; CHECK-NEXT:    shl.s 5, r3, r3
; CHECK-NEXT:    add r1, r3, r3
; CHECK-NEXT:  .BB5_1: ; %load-store-loop
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldpi r2, r4, r2
; CHECK-NEXT:    stmi.h r1, r4, r1
; CHECK-NEXT:    sub! r1, r3, r0
; CHECK-NEXT:    jump.ne @.BB5_1
; CHECK-NEXT:  ; %bb.2: ; %memcpy-split
; CHECK-NEXT:    ret
  br label %load-store-loop

load-store-loop:                                  ; preds = %load-store-loop, %0
  %loop-index = phi i256 [ 0, %0 ], [ %4, %load-store-loop ]
  %1 = getelementptr inbounds i256, i256 addrspace(3)* %src, i256 %loop-index
  %2 = load i256, i256 addrspace(3)* %1, align 1
  %3 = getelementptr inbounds i256, i256 addrspace(1)* %dest, i256 %loop-index
  store i256 %2, i256 addrspace(1)* %3, align 1
  %4 = add i256 %loop-index, 1
  %5 = icmp ult i256 %4, %size
  br i1 %5, label %load-store-loop, label %memcpy-split

memcpy-split:                                     ; preds = %load-store-loop
  ret void
}
