; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -O3 < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S32-a:256:256"
target triple = "eravm"

define i256 @test(i256 %dummy, ptr addrspace(3) %0) {
; CHECK-LABEL: test:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    and 255, r2, r1
; CHECK-NEXT:    ret
  %ptrtoint = ptrtoint ptr addrspace(3) %0 to i256
  %and = and i256 %ptrtoint, 255
  ret i256 %and
}
