; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -O3 < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S32-a:256:256"
target triple = "eravm"

declare void @use(i256)

define i256 @test(i256 %in, i1 %cond) {
; CHECK-LABEL: test:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    sub! r2, r0, r0
; CHECK-NEXT:    jump.eq @.BB0_2
; CHECK-NEXT:  ; %bb.1: ; %bb1
; CHECK-NEXT:    and code[@CPI0_0], r1, r1
; CHECK-NEXT:    call r0, @use, @DEFAULT_UNWIND
; CHECK-NEXT:    add r0, r0, r1
; CHECK-NEXT:    ret
; CHECK-NEXT:  .BB0_2: ; %bb2
; CHECK-NEXT:    add 5, r0, r1
; CHECK-NEXT:    call r0, @use, @DEFAULT_UNWIND
; CHECK-NEXT:    add 1, r0, r1
; CHECK-NEXT:    ret
entry:
  %and = and i256 %in, 123456789
  br i1 %cond, label %bb1, label %bb2

bb1:
  call void @use(i256 %and)
  ret i256 0

bb2:
  call void @use(i256 5)
  ret i256 1
}
