; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -O0 < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S32-a:256:256"
target triple = "eravm"

define i256 @test_length(i256 %arg1) {
; CHECK-LABEL: test_length:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    sub.s! 36, r1, r2
; CHECK-NEXT:    add r0, r0, r2
; CHECK-NEXT:    add.lt code[@CPI0_0], r0, r2
; CHECK-NEXT:    and code[@CPI0_0], r1, r3
; CHECK-NEXT:    sub! r3, r0, r1
; CHECK-NEXT:    add r0, r0, r1
; CHECK-NEXT:    add.gt code[@CPI0_0], r0, r1
; CHECK-NEXT:    sub.s! code[@CPI0_0], r3, r3
; CHECK-NEXT:    add.ne r2, r0, r1
; CHECK-NEXT:    sub! r1, r0, r1
; CHECK-NEXT:    add 0, r0, r1
; CHECK-NEXT:    add.ne 1, r0, r1
; CHECK-NEXT:    ret
entry:
  %comparison_result24 = icmp slt i256 35, %arg1
  %comparison_result_extended25 = zext i1 %comparison_result24 to i256

  %comparison_result26 = icmp eq i256 %comparison_result_extended25, 0
  %comparison_result_extended27 = zext i1 %comparison_result26 to i256

  %if_condition_compared28 = icmp ne i256 %comparison_result_extended27, 0
  %ret_value = zext i1 %if_condition_compared28 to i256
  ret i256 %ret_value
}
