; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -O3 < %s | FileCheck %s
;
; Check code generation for ALL select addressing modes:
; * in0/in1 in {register, immediate, code, stack},
; * out in {register, stack}.

target triple = "eravm"
target datalayout = "E-p:256:256-i256:256:256-S32-a:256:256"

@val = addrspace(4) global i256 42
@val2 = addrspace(4) global i256 17

define i256 @selrrr(i1 %cond, i256 %x, i256 %y) {
; CHECK-LABEL: selrrr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    add.eq r3, r0, r2
; CHECK-NEXT:    add r2, r0, r1
; CHECK-NEXT:    ret
  %s = select i1 %cond, i256 %x, i256 %y
  ret i256 %s
}

define i256 @selirr(i1 %cond, i256 %y) {
; CHECK-LABEL: selirr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    add.ne 12345, r0, r2
; CHECK-NEXT:    add r2, r0, r1
; CHECK-NEXT:    ret
  %s = select i1 %cond, i256 12345, i256 %y
  ret i256 %s
}

define i256 @selcrr(i1 %cond, i256 %y) {
; CHECK-LABEL: selcrr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    add.ne code[@val], r0, r2
; CHECK-NEXT:    add r2, r0, r1
; CHECK-NEXT:    ret
  %c = load i256, ptr addrspace(4) @val
  %s = select i1 %cond, i256 %c, i256 %y
  ret i256 %s
}

define i256 @selsrr(i1 %cond, ptr %p, i256 %y) {
; CHECK-LABEL: selsrr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r2, r1
; CHECK-NEXT:    add.ne stack[r1], r0, r3
; CHECK-NEXT:    add r3, r0, r1
; CHECK-NEXT:    ret
  %l = load i256, ptr %p
  %s = select i1 %cond, i256 %l, i256 %y
  ret i256 %s
}

define i256 @selrir(i1 %cond, i256 %x) {
; CHECK-LABEL: selrir:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    add.eq 12345, r0, r2
; CHECK-NEXT:    add r2, r0, r1
; CHECK-NEXT:    ret
  %s = select i1 %cond, i256 %x, i256 12345
  ret i256 %s
}

define i256 @seliir(i1 %cond) {
; CHECK-LABEL: seliir:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    add 777, r0, r1
; CHECK-NEXT:    add.ne 12345, r0, r1
; CHECK-NEXT:    ret
  %s = select i1 %cond, i256 12345, i256 777
  ret i256 %s
}

define i256 @selcir(i1 %cond) {
; CHECK-LABEL: selcir:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    add 777, r0, r1
; CHECK-NEXT:    add.ne code[@val], r0, r1
; CHECK-NEXT:    ret
  %c = load i256, ptr addrspace(4) @val
  %s = select i1 %cond, i256 %c, i256 777
  ret i256 %s
}

define i256 @selsir(i1 %cond, ptr %p) {
; CHECK-LABEL: selsir:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r2, r2
; CHECK-NEXT:    add 777, r0, r1
; CHECK-NEXT:    add.ne stack[r2], r0, r1
; CHECK-NEXT:    ret
  %l = load i256, ptr %p
  %s = select i1 %cond, i256 %l, i256 777
  ret i256 %s
}

define i256 @selrcr(i1 %cond, i256 %x) {
; CHECK-LABEL: selrcr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    add.eq code[@val], r0, r2
; CHECK-NEXT:    add r2, r0, r1
; CHECK-NEXT:    ret
  %c = load i256, ptr addrspace(4) @val
  %s = select i1 %cond, i256 %x, i256 %c
  ret i256 %s
}

define i256 @selicr(i1 %cond) {
; CHECK-LABEL: selicr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    add code[@val], r0, r1
; CHECK-NEXT:    add.ne 12345, r0, r1
; CHECK-NEXT:    ret
  %c = load i256, ptr addrspace(4) @val
  %s = select i1 %cond, i256 12345, i256 %c
  ret i256 %s
}

define i256 @selccr(i1 %cond) {
; CHECK-LABEL: selccr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    add code[@val2], r0, r1
; CHECK-NEXT:    add.ne code[@val], r0, r1
; CHECK-NEXT:    ret
  %c1 = load i256, ptr addrspace(4) @val
  %c2 = load i256, ptr addrspace(4) @val2
  %s = select i1 %cond, i256 %c1, i256 %c2
  ret i256 %s
}

define i256 @selscr(i1 %cond, ptr %p) {
; CHECK-LABEL: selscr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r2, r2
; CHECK-NEXT:    add code[@val], r0, r1
; CHECK-NEXT:    add.ne stack[r2], r0, r1
; CHECK-NEXT:    ret
  %l = load i256, ptr %p
  %c = load i256, ptr addrspace(4) @val
  %s = select i1 %cond, i256 %l, i256 %c
  ret i256 %s
}

define i256 @selrsr(i1 %cond, i256 %x, ptr %p) {
; CHECK-LABEL: selrsr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r3, r1
; CHECK-NEXT:    add.eq stack[r1], r0, r2
; CHECK-NEXT:    add r2, r0, r1
; CHECK-NEXT:    ret
  %l = load i256, ptr %p
  %s = select i1 %cond, i256 %x, i256 %l
  ret i256 %s
}

define i256 @selisr(i1 %cond, ptr %p) {
; CHECK-LABEL: selisr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r2, r2
; CHECK-NEXT:    add stack[r2], r0, r1
; CHECK-NEXT:    add.ne 12345, r0, r1
; CHECK-NEXT:    ret
  %l = load i256, ptr %p
  %s = select i1 %cond, i256 12345, i256 %l
  ret i256 %s
}

define i256 @selcsr(i1 %cond, ptr %p) {
; CHECK-LABEL: selcsr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r2, r2
; CHECK-NEXT:    add stack[r2], r0, r1
; CHECK-NEXT:    add.ne code[@val], r0, r1
; CHECK-NEXT:    ret
  %c = load i256, ptr addrspace(4) @val
  %l = load i256, ptr %p
  %s = select i1 %cond, i256 %c, i256 %l
  ret i256 %s
}

define i256 @selssr(i1 %cond, ptr %p, ptr %q) {
; CHECK-LABEL: selssr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r2, r2
; CHECK-NEXT:    shr.s 5, r3, r3
; CHECK-NEXT:    add stack[r3], r0, r1
; CHECK-NEXT:    add.ne stack[r2], r0, r1
; CHECK-NEXT:    ret
  %l1 = load i256, ptr %p
  %l2 = load i256, ptr %q
  %s = select i1 %cond, i256 %l1, i256 %l2
  ret i256 %s
}

; ---------------- stack result (out = s, the ce9fcdc6 family) ----------------
; store through a register pointer: absolute stack output with a register base.

define void @selrrs(i1 %cond, i256 %x, i256 %y, ptr %out) {
; CHECK-LABEL: selrrs:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r4, r1
; CHECK-NEXT:    add r3, r0, stack[r1]
; CHECK-NEXT:    add.ne r2, r0, stack[r1]
; CHECK-NEXT:    ret
  %s = select i1 %cond, i256 %x, i256 %y
  store i256 %s, ptr %out
  ret void
}

define void @selris(i1 %cond, i256 %x, ptr %out) {
; CHECK-LABEL: selris:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r3, r1
; CHECK-NEXT:    add 12345, r0, stack[r1]
; CHECK-NEXT:    add.ne r2, r0, stack[r1]
; CHECK-NEXT:    ret
  %s = select i1 %cond, i256 %x, i256 12345
  store i256 %s, ptr %out
  ret void
}

define void @selirs(i1 %cond, i256 %y, ptr %out) {
; CHECK-LABEL: selirs:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r3, r1
; CHECK-NEXT:    add r2, r0, stack[r1]
; CHECK-NEXT:    add.ne 12345, r0, stack[r1]
; CHECK-NEXT:    ret
  %s = select i1 %cond, i256 12345, i256 %y
  store i256 %s, ptr %out
  ret void
}

define void @seliis(i1 %cond, ptr %out) {
; CHECK-LABEL: seliis:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r2, r1
; CHECK-NEXT:    add 777, r0, stack[r1]
; CHECK-NEXT:    add.ne 12345, r0, stack[r1]
; CHECK-NEXT:    ret
  %s = select i1 %cond, i256 12345, i256 777
  store i256 %s, ptr %out
  ret void
}

define void @selrcs(i1 %cond, i256 %x, ptr %out) {
; CHECK-LABEL: selrcs:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r3, r1
; CHECK-NEXT:    add code[@val], r0, stack[r1]
; CHECK-NEXT:    add.ne r2, r0, stack[r1]
; CHECK-NEXT:    ret
  %c = load i256, ptr addrspace(4) @val
  %s = select i1 %cond, i256 %x, i256 %c
  store i256 %s, ptr %out
  ret void
}

define void @selics(i1 %cond, ptr %out) {
; CHECK-LABEL: selics:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r2, r1
; CHECK-NEXT:    add code[@val], r0, stack[r1]
; CHECK-NEXT:    add.ne 12345, r0, stack[r1]
; CHECK-NEXT:    ret
  %c = load i256, ptr addrspace(4) @val
  %s = select i1 %cond, i256 12345, i256 %c
  store i256 %s, ptr %out
  ret void
}

define void @selcrs(i1 %cond, i256 %y, ptr %out) {
; CHECK-LABEL: selcrs:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r3, r1
; CHECK-NEXT:    add r2, r0, stack[r1]
; CHECK-NEXT:    add.ne code[@val], r0, stack[r1]
; CHECK-NEXT:    ret
  %c = load i256, ptr addrspace(4) @val
  %s = select i1 %cond, i256 %c, i256 %y
  store i256 %s, ptr %out
  ret void
}

define void @selcis(i1 %cond, ptr %out) {
; CHECK-LABEL: selcis:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r2, r1
; CHECK-NEXT:    add 777, r0, stack[r1]
; CHECK-NEXT:    add.ne code[@val], r0, stack[r1]
; CHECK-NEXT:    ret
  %c = load i256, ptr addrspace(4) @val
  %s = select i1 %cond, i256 %c, i256 777
  store i256 %s, ptr %out
  ret void
}

define void @selccs(i1 %cond, ptr %out) {
; CHECK-LABEL: selccs:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    add code[@val], r0, r3
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r2, r1
; CHECK-NEXT:    add code[@val2], r0, stack[r1]
; CHECK-NEXT:    add.ne r3, r0, stack[r1]
; CHECK-NEXT:    ret
  %c1 = load i256, ptr addrspace(4) @val
  %c2 = load i256, ptr addrspace(4) @val2
  %s = select i1 %cond, i256 %c1, i256 %c2
  store i256 %s, ptr %out
  ret void
}

define void @selrss(i1 %cond, i256 %x, ptr %p, ptr %out) {
; CHECK-LABEL: selrss:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r3, r1
; CHECK-NEXT:    shr.s 5, r4, r3
; CHECK-NEXT:    add stack[r1], r0, stack[r3]
; CHECK-NEXT:    add.ne r2, r0, stack[r3]
; CHECK-NEXT:    ret
  %l = load i256, ptr %p
  %s = select i1 %cond, i256 %x, i256 %l
  store i256 %s, ptr %out
  ret void
}

define void @seliss(i1 %cond, ptr %p, ptr %out) {
; CHECK-LABEL: seliss:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r2, r1
; CHECK-NEXT:    shr.s 5, r3, r2
; CHECK-NEXT:    add stack[r1], r0, stack[r2]
; CHECK-NEXT:    add.ne 12345, r0, stack[r2]
; CHECK-NEXT:    ret
  %l = load i256, ptr %p
  %s = select i1 %cond, i256 12345, i256 %l
  store i256 %s, ptr %out
  ret void
}

define void @selcss(i1 %cond, ptr %p, ptr %out) {
; CHECK-LABEL: selcss:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    add code[@val], r0, r4
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r2, r1
; CHECK-NEXT:    shr.s 5, r3, r2
; CHECK-NEXT:    add stack[r1], r0, stack[r2]
; CHECK-NEXT:    add.ne r4, r0, stack[r2]
; CHECK-NEXT:    ret
  %c = load i256, ptr addrspace(4) @val
  %l = load i256, ptr %p
  %s = select i1 %cond, i256 %c, i256 %l
  store i256 %s, ptr %out
  ret void
}

define void @selscs(i1 %cond, ptr %p, ptr %out) {
; CHECK-LABEL: selscs:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    add code[@val], r0, r4
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r2, r1
; CHECK-NEXT:    shr.s 5, r3, r2
; CHECK-NEXT:    add r4, r0, stack[r2]
; CHECK-NEXT:    add.ne stack[r1], r0, stack[r2]
; CHECK-NEXT:    ret
  %l = load i256, ptr %p
  %c = load i256, ptr addrspace(4) @val
  %s = select i1 %cond, i256 %l, i256 %c
  store i256 %s, ptr %out
  ret void
}

define void @selsrs(i1 %cond, ptr %p, i256 %y, ptr %out) {
; CHECK-LABEL: selsrs:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r2, r1
; CHECK-NEXT:    shr.s 5, r4, r2
; CHECK-NEXT:    add r3, r0, stack[r2]
; CHECK-NEXT:    add.ne stack[r1], r0, stack[r2]
; CHECK-NEXT:    ret
  %l = load i256, ptr %p
  %s = select i1 %cond, i256 %l, i256 %y
  store i256 %s, ptr %out
  ret void
}

define void @selsis(i1 %cond, ptr %p, ptr %out) {
; CHECK-LABEL: selsis:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r2, r1
; CHECK-NEXT:    shr.s 5, r3, r2
; CHECK-NEXT:    add 12345, r0, stack[r2]
; CHECK-NEXT:    add.ne stack[r1], r0, stack[r2]
; CHECK-NEXT:    ret
  %l = load i256, ptr %p
  %s = select i1 %cond, i256 %l, i256 12345
  store i256 %s, ptr %out
  ret void
}

define void @selsss(i1 %cond, ptr %p, ptr %q, ptr %out) {
; CHECK-LABEL: selsss:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r2, r1
; CHECK-NEXT:    shr.s 5, r3, r2
; CHECK-NEXT:    add stack[r2], r0, r3
; CHECK-NEXT:    add.ne stack[r1], r0, r3
; CHECK-NEXT:    shr.s 5, r4, r1
; CHECK-NEXT:    add r3, r0, stack[r1]
; CHECK-NEXT:    ret
  %l1 = load i256, ptr %p
  %l2 = load i256, ptr %q
  %s = select i1 %cond, i256 %l1, i256 %l2
  store i256 %s, ptr %out
  ret void
}

; constant-pool OFFSET forms: the code-page half of the defect keeps byte offsets.
; @arr[2] is cell 2; an unconverted operand addresses it as byte 64.

@arr = addrspace(4) global [4 x i256] [i256 11, i256 22, i256 33, i256 44]

define void @selcrs_off(i1 %cond, i256 %y, ptr %out) {
; CHECK-LABEL: selcrs_off:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r3, r1
; CHECK-NEXT:    add r2, r0, stack[r1]
; CHECK-NEXT:    add.ne code[@arr+2], r0, stack[r1]
; CHECK-NEXT:    ret
  %c = load i256, ptr addrspace(4) getelementptr inbounds ([4 x i256], ptr addrspace(4) @arr, i256 0, i256 2)
  %s = select i1 %cond, i256 %c, i256 %y
  store i256 %s, ptr %out
  ret void
}

define void @selcis_off(i1 %cond, ptr %out) {
; CHECK-LABEL: selcis_off:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    sub! r1, r0, r0
; CHECK-NEXT:    shr.s 5, r2, r1
; CHECK-NEXT:    add 777, r0, stack[r1]
; CHECK-NEXT:    add.ne code[@arr+2], r0, stack[r1]
; CHECK-NEXT:    ret
  %c = load i256, ptr addrspace(4) getelementptr inbounds ([4 x i256], ptr addrspace(4) @arr, i256 0, i256 2)
  %s = select i1 %cond, i256 %c, i256 777
  store i256 %s, ptr %out
  ret void
}
