; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

define i256 @addrrr(i256 %rs1, i256 %rs2) nounwind {
; CHECK-LABEL: addrrr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    ADD
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = add i256 %rs1, %rs2
  ret i256 %res
}

define i256 @addrri(i256 %rs1) nounwind {
; CHECK-LABEL: addrri:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH9 18446744073709551616
; CHECK-NEXT:    ADD
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = add i256 %rs1, 18446744073709551616 ; 65-bits
  ret i256 %res
}

define i256 @subrri(i256 %rs1) nounwind {
; CHECK-LABEL: subrri:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 1
; CHECK-NEXT:    ADD
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = sub i256 %rs1, -1
  ret i256 %res
}
