; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -O3 < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

define i256 @test(i256 %arg) {
; CHECK-LABEL: test:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 0xA
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    DUP3
; CHECK-NEXT:    SLT
; CHECK-NEXT:    MUL
; CHECK-NEXT:    PUSH1 0x14
; CHECK-NEXT:    SUB
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    DUP3
; CHECK-NEXT:    PUSH1 0x5
; CHECK-NEXT:    SUB
; CHECK-NEXT:    SWAP2
; CHECK-NEXT:    SGT
; CHECK-NEXT:    MUL
; CHECK-NEXT:    ADD
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP
entry:
  %cmp1 = icmp slt i256 %arg, 0
  br i1 %cmp1, label %bb1, label %bb2

bb1:
  br label %bb2

bb2:
  %phi1 = phi i256 [ 20, %entry ], [ 10, %bb1 ]
  %cmp2 = icmp sgt i256 %arg, 0
  br i1 %cmp2, label %bb3, label %bb4

bb3:
  br label %bb4

bb4:
  %phi2 = phi i256 [ %phi1, %bb2 ], [ 5, %bb3 ]
  ret i256 %phi2
}
