; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -O3 < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

declare void @llvm.evm.revert(ptr addrspace(1) readonly, i256) #0

; Ensure that, before merging two basic blocks, the condition code is removed from the top of the
; stack in the preceding block.
define void @__entry(i1 %comparison_result) {
; CHECK-LABEL: __entry:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    POP
; CHECK-NEXT:    PUSH1 0x1
; CHECK-NEXT:    AND
; CHECK-NEXT:    POP
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    REVERT
entry:
  br i1 %comparison_result, label %if_main, label %if_join

if_main:
  %calldata_load_result = load i256, ptr addrspace(2) null, align 4294967296
  br label %if_join

if_join:
  tail call void @llvm.evm.revert(ptr addrspace(1) null, i256 0)
  unreachable
}

attributes #0 = { noreturn nounwind memory(argmem: read) }
