; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

; Two-value comparisons

define void @br_eq(i256 %a, i256 %b) {
; CHECK-LABEL: br_eq:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP2
; CHECK-NEXT:    POP
; CHECK-NEXT:    EQ
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    PUSH4 @.BB0_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB0_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp eq i256 %a, %b
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

define void @br_ne(i256 %a, i256 %b) {
; CHECK-LABEL: br_ne:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP2
; CHECK-NEXT:    POP
; CHECK-NEXT:    EQ
; CHECK-NEXT:    PUSH4 @.BB1_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB1_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp ne i256 %a, %b
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

define void @br_ugt(i256 %a, i256 %b) {
; CHECK-LABEL: br_ugt:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    SWAP2
; CHECK-NEXT:    POP
; CHECK-NEXT:    GT
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    PUSH4 @.BB2_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB2_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp ugt i256 %a, %b
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

define void @br_uge(i256 %a, i256 %b) {
; CHECK-LABEL: br_uge:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    SWAP2
; CHECK-NEXT:    POP
; CHECK-NEXT:    LT
; CHECK-NEXT:    PUSH4 @.BB3_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB3_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp uge i256 %a, %b
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

define void @br_ult(i256 %a, i256 %b) {
; CHECK-LABEL: br_ult:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    SWAP2
; CHECK-NEXT:    POP
; CHECK-NEXT:    LT
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    PUSH4 @.BB4_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB4_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp ult i256 %a, %b
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

define void @br_ule(i256 %a, i256 %b) {
; CHECK-LABEL: br_ule:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    SWAP2
; CHECK-NEXT:    POP
; CHECK-NEXT:    GT
; CHECK-NEXT:    PUSH4 @.BB5_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB5_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp ule i256 %a, %b
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

define void @br_sgt(i256 %a, i256 %b) {
; CHECK-LABEL: br_sgt:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    SWAP2
; CHECK-NEXT:    POP
; CHECK-NEXT:    SGT
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    PUSH4 @.BB6_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB6_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp sgt i256 %a, %b
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

define void @br_sge(i256 %a, i256 %b) {
; CHECK-LABEL: br_sge:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    SWAP2
; CHECK-NEXT:    POP
; CHECK-NEXT:    SLT
; CHECK-NEXT:    PUSH4 @.BB7_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB7_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp sge i256 %a, %b
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

define void @br_slt(i256 %a, i256 %b) {
; CHECK-LABEL: br_slt:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    SWAP2
; CHECK-NEXT:    POP
; CHECK-NEXT:    SLT
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    PUSH4 @.BB8_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB8_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp slt i256 %a, %b
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

define void @br_sle(i256 %a, i256 %b) {
; CHECK-LABEL: br_sle:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    SWAP2
; CHECK-NEXT:    POP
; CHECK-NEXT:    SGT
; CHECK-NEXT:    PUSH4 @.BB9_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB9_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp sle i256 %a, %b
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

; One-value comparisons with zero

define void @br_eq_0(i256 %a) {
; CHECK-LABEL: br_eq_0:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    POP
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    EQ
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    PUSH4 @.BB10_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB10_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp eq i256 %a, 0
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

define void @br_ne_0(i256 %a) {
; CHECK-LABEL: br_ne_0:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    POP
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    PUSH4 @.BB11_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB11_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp ne i256 %a, 0
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

define void @br_ugt_0(i256 %a) {
; CHECK-LABEL: br_ugt_0:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    POP
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    PUSH4 @.BB12_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB12_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp ugt i256 %a, 0
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

define void @br_uge_0(i256 %a) {
; CHECK-LABEL: br_uge_0:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    POP
; CHECK-NEXT:    POP
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    PUSH4 @.BB13_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB13_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp uge i256 %a, 0
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

define void @br_ult_0(i256 %a) {
; CHECK-LABEL: br_ult_0:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    POP
; CHECK-NEXT:    POP
; CHECK-NEXT:    PUSH1 0x1
; CHECK-NEXT:    PUSH4 @.BB14_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB14_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp ult i256 %a, 0
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

define void @br_ule_0(i256 %a) {
; CHECK-LABEL: br_ule_0:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    POP
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    EQ
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    PUSH4 @.BB15_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB15_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp ule i256 %a, 0
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

define void @br_sgt_0(i256 %a) {
; CHECK-LABEL: br_sgt_0:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 0x1
; CHECK-NEXT:    SWAP2
; CHECK-NEXT:    POP
; CHECK-NEXT:    SLT
; CHECK-NEXT:    PUSH4 @.BB16_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB16_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp sgt i256 %a, 0
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

define void @br_sge_0(i256 %a) {
; CHECK-LABEL: br_sge_0:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    SWAP2
; CHECK-NEXT:    POP
; CHECK-NEXT:    SLT
; CHECK-NEXT:    PUSH4 @.BB17_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB17_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp sge i256 %a, 0
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

define void @br_slt_0(i256 %a) {
; CHECK-LABEL: br_slt_0:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    NOT
; CHECK-NEXT:    SWAP2
; CHECK-NEXT:    POP
; CHECK-NEXT:    SGT
; CHECK-NEXT:    PUSH4 @.BB18_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB18_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp slt i256 %a, 0
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

define void @br_sle_0(i256 %a) {
; CHECK-LABEL: br_sle_0:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    SWAP2
; CHECK-NEXT:    POP
; CHECK-NEXT:    SGT
; CHECK-NEXT:    PUSH4 @.BB19_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1: ; %true
; CHECK-NEXT:  .BB19_2: ; %false
; CHECK-NEXT:    JUMPDEST
  %cond = icmp sle i256 %a, 0
  br i1 %cond, label %true, label %false
true:
  unreachable
false:
  unreachable
}

