; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -O3 < %s | FileCheck %s

; Test that we are using different unfold for speed and size tests.

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm-unknown-unknown"

define i256 @test_speed() {
; CHECK-LABEL: test_speed:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH3 0xFFFFFF
; CHECK-NEXT:    PUSH1 0xE8
; CHECK-NEXT:    SHL
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP
  ret i256 115792082335569848633007197573932045576244532214531591869071028845388905840640
}

define i256 @test_size() minsize {
; CHECK-LABEL: test_size:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    NOT
; CHECK-NEXT:    PUSH1 0xE8
; CHECK-NEXT:    SHL
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP
  ret i256 115792082335569848633007197573932045576244532214531591869071028845388905840640
}
