; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -O3 < %s | FileCheck %s
target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm-unknown-unknown"

declare void @llvm.evm.return(ptr addrspace(1), i256) noreturn

; This file tests how constants are unfolded in OptForSize mode.

; 0x4e487b7100000000000000000000000000000000000000000000000000000000
define void @test1() #1 {
; CHECK-LABEL: test1:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH4 0x4E487B71
; CHECK-NEXT:    PUSH1 0xE0
; CHECK-NEXT:    SHL
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 35408467139433450592217433187231851964531694900788300625387963629091585785856)
  unreachable
}

; 0x00000000FFFFFF00000000000000000000000000000000000000000000000000
define void @test2() #1 {
; CHECK-LABEL: test2:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH3 0xFFFFFF
; CHECK-NEXT:    PUSH1 0xC8
; CHECK-NEXT:    SHL
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 26959945060212595535676739545057538332474541900337578698310774947840)
  unreachable
}

; 0x00000000FFFFFFFFFFFF00000000000000000000000000000000000000000000
define void @test3() #1 {
; CHECK-LABEL: test3:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH6 0xFFFFFFFFFFFF
; CHECK-NEXT:    PUSH1 0xB0
; CHECK-NEXT:    SHL
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 26959946667150544013695710968965983276947947528216596309908473774080)
  unreachable
}

; 0x00000000FFFFFFFFFFFFFF000000000000000000000000000000000000000000
define void @test4() #1 {
; CHECK-LABEL: test4:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH7 0xFFFFFFFFFFFFFF
; CHECK-NEXT:    PUSH1 0xA8
; CHECK-NEXT:    SHL
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 26959946667150639420522595930308483613493827247172119449184879247360)
  unreachable
}

; 0xFFFFFF0000000000000000000000000000000000000000000000000000000000
define void @test5() #1 {
; CHECK-LABEL: test5:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    NOT
; CHECK-NEXT:    PUSH1 0xE8
; CHECK-NEXT:    SHL
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 115792082335569848633007197573932045576244532214531591869071028845388905840640)
  unreachable
}

; 0xFFFFFFFF00000000000000000000000000000000000000000000000000000000
define void @test6() #1 {
; CHECK-LABEL: test6:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    NOT
; CHECK-NEXT:    PUSH1 0xE0
; CHECK-NEXT:    SHL
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 115792089210356248756420345214020892766250353992003419616917011526809519390720)
  unreachable
}

; 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
define void @test7() #1 {
; CHECK-LABEL: test7:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    NOT
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 -1)
  unreachable
}


; 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000
define void @test8() #1 {
; CHECK-LABEL: test8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    NOT
; CHECK-NEXT:    PUSH1 0x81
; CHECK-NEXT:    SHL
; CHECK-NEXT:    PUSH1 0x1
; CHECK-NEXT:    SHR
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 57896044618658097711785492504343953926294709965899343556265417396524796608512)
  unreachable
}

; 0x000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFFF
define void @test11() #1 {
; CHECK-LABEL: test11:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    NOT
; CHECK-NEXT:    PUSH1 0xC0
; CHECK-NEXT:    SHR
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 18446744073709551615)
  unreachable
}

; 0x000000000000000000000000000000000000000000000000FFFFFFFAFFFFFFFF
define void @test12() #1 {
; CHECK-LABEL: test12:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH8 0xFFFFFFFAFFFFFFFF
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 18446744052234715135)
  unreachable
}

; 0x000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFE0
define void @test13() #1 {
; CHECK-LABEL: test13:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH8 0xFFFFFFFFFFFFFFE0
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 18446744073709551584)
  unreachable
}

; 0x00000000000000000000000000000000000000000000FFFFFFFFFFFFFFFFFFE0
define void @test14() #1 {
; CHECK-LABEL: test14:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH10 0xFFFFFFFFFFFFFFFFFFE0
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 1208925819614629174706144)
  unreachable
}

; 0x00000000000000000000000000000000000000FFFFFFFFFFFFFFFFAFFFFFFFFF
define void @test15() #1 {
; CHECK-LABEL: test15:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH13 0xFFFFFFFFFFFFFFFFAFFFFFFFFF
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 20282409603651670423603653902335)
  unreachable
}

; 0x00000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
define void @test16() #1 {
; CHECK-LABEL: test16:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    NOT
; CHECK-NEXT:    PUSH1 0x54
; CHECK-NEXT:    SHR
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 5986310706507378352962293074805895248510699696029695)
  unreachable
}

; 0x00000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFAE0000000000000000000000
define void @test17() #1 {
; CHECK-LABEL: test17:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 0x28
; CHECK-NEXT:    NOT
; CHECK-NEXT:    PUSH1 0x82
; CHECK-NEXT:    SHL
; CHECK-NEXT:    PUSH1 0x29
; CHECK-NEXT:    SHR
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 52656145834278593348959013841835216134069776894924259991723442176)
  unreachable
}

; 0x0000000000000000000000000000000100000000000000000000000000000000
define void @test18() #1 {
; CHECK-LABEL: test18:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 0x1
; CHECK-NEXT:    PUSH1 0x80
; CHECK-NEXT:    SHL
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 340282366920938463463374607431768211456)
  unreachable
}

; 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE
define void @test19() #1 {
; CHECK-LABEL: test19:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 0x1
; CHECK-NEXT:    NOT
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 115792089237316195423570985008687907853269984665640564039457584007913129639934)
  unreachable
}

; 0xFFFFFFFFFFFFFFFFFFFFFFFFF7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
define void @test20() #1 {
; CHECK-LABEL: test20:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 0x1
; CHECK-NEXT:    PUSH1 0x9B
; CHECK-NEXT:    SHL
; CHECK-NEXT:    NOT
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 115792089237316195423570985008642235927103393949446698888435200163548881747967)
  unreachable
}

; 0x00000000000001000000000000000000000000000000000000000000000000FF
define void @test21() #1 {
; CHECK-LABEL: test21:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH26 0x1000000000000000000000000000000000000000000000000FF
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 1606938044258990275541962092341162602522202993782792835301631)
  unreachable
}

attributes #1 = { minsize nofree nounwind noreturn optsize }
