; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=early-cse -S < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

declare i256 @llvm.evm.addmod(i256, i256, i256)

define i256 @test_addmod1() {
; CHECK-LABEL: define i256 @test_addmod1() {
; CHECK-NEXT:    ret i256 1
;

  ; Params are treated as unsigned values
  %res = call i256 @llvm.evm.addmod(i256 -1, i256 2, i256 2)
  ret i256 %res
}

define i256 @test_addmod2() {
; CHECK-LABEL: define i256 @test_addmod2() {
; CHECK-NEXT:    ret i256 4
;

  %res = call i256 @llvm.evm.addmod(i256 48, i256 1, i256 5)
  ret i256 %res
}

define i256 @test_addmod3() {
; CHECK-LABEL: define i256 @test_addmod3() {
; CHECK-NEXT:    ret i256 poison
;

  %res = call i256 @llvm.evm.addmod(i256 48, i256 undef, i256 5)
  ret i256 %res
}

define i256 @test_addmod4() {
; CHECK-LABEL: define i256 @test_addmod4() {
; CHECK-NEXT:    ret i256 poison
;

  %res = call i256 @llvm.evm.addmod(i256 undef, i256 48, i256 5)
  ret i256 %res
}

define i256 @test_addmod5() {
; CHECK-LABEL: define i256 @test_addmod5() {
; CHECK-NEXT:    ret i256 poison
;

  %res = call i256 @llvm.evm.addmod(i256 48, i256 1, i256 undef)
  ret i256 %res
}
