; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=early-cse -S < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

declare i256 @llvm.evm.mulmod(i256, i256, i256)

define i256 @test_mulmod1() {
; CHECK-LABEL: define i256 @test_mulmod1() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.mulmod(i256 -2, i256 -2, i256 3)
; CHECK-NEXT:    ret i256 [[RES]]
;

  ; Params are treated as unsigned values
  %res = call i256 @llvm.evm.mulmod(i256 -2, i256 -2, i256 3)
  ret i256 %res
}

define i256 @test_mulmod2() {
; CHECK-LABEL: define i256 @test_mulmod2() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.mulmod(i256 3, i256 17, i256 7)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.mulmod(i256 3, i256 17, i256 7)
  ret i256 %res
}

define i256 @test_mulmod3() {
; CHECK-LABEL: define i256 @test_mulmod3() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.mulmod(i256 undef, i256 17, i256 7)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.mulmod(i256 undef, i256 17, i256 7)
  ret i256 %res
}

define i256 @test_mulmod4() {
; CHECK-LABEL: define i256 @test_mulmod4() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.mulmod(i256 17, i256 undef, i256 7)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.mulmod(i256 17, i256 undef, i256 7)
  ret i256 %res
}

define i256 @test_mulmod5() {
; CHECK-LABEL: define i256 @test_mulmod5() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.mulmod(i256 3, i256 17, i256 undef)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.mulmod(i256 3, i256 17, i256 undef)
  ret i256 %res
}
