; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -O3 < %s | FileCheck %s
target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm-unknown-unknown"

declare void @llvm.evm.return(ptr addrspace(1), i256) noreturn

; This file tests how constants are unfolded in non-OptForSize mode.

; 0x4e487b7100000000000000000000000000000000000000000000000000000000
define void @test1() #1 {
; CHECK-LABEL: test1:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH4 0x4E487B71
; CHECK-NEXT:    PUSH1 0xE0
; CHECK-NEXT:    SHL
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 35408467139433450592217433187231851964531694900788300625387963629091585785856)
  unreachable
}

; 0x00000000FFFFFF00000000000000000000000000000000000000000000000000
define void @test2() #1 {
; CHECK-LABEL: test2:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH3 0xFFFFFF
; CHECK-NEXT:    PUSH1 0xC8
; CHECK-NEXT:    SHL
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 26959945060212595535676739545057538332474541900337578698310774947840)
  unreachable
}

; 0xFFFFFF0000000000000000000000000000000000000000000000000000000000
define void @test3() #1 {
; CHECK-LABEL: test3:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH3 0xFFFFFF
; CHECK-NEXT:    PUSH1 0xE8
; CHECK-NEXT:    SHL
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 115792082335569848633007197573932045576244532214531591869071028845388905840640)
  unreachable
}

; 0xFFFFFFFF00000000000000000000000000000000000000000000000000000000
define void @test4() #1 {
; CHECK-LABEL: test4:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH4 0xFFFFFFFF
; CHECK-NEXT:    PUSH1 0xE0
; CHECK-NEXT:    SHL
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 115792089210356248756420345214020892766250353992003419616917011526809519390720)
  unreachable
}

; 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
define void @test5() #1 {
; CHECK-LABEL: test5:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    NOT
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 -1)
  unreachable
}

; 0x0000000000000000000000000000000100000000000000000000000000000000
define void @test6() #1 {
; CHECK-LABEL: test6:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 0x1
; CHECK-NEXT:    PUSH1 0x80
; CHECK-NEXT:    SHL
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 340282366920938463463374607431768211456)
  unreachable
}

attributes #1 = { nofree nounwind noreturn }
