; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -O3 --evm-stack-region-size=32 --evm-stack-region-offset=128 --evm-constant-spill-threshold=2 --enable-constant-spilling-without-unsafe-asm < %s | FileCheck %s
target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm-unknown-unknown"

declare void @llvm.evm.return(ptr addrspace(1), i256) noreturn

define void @entry() #1 {
; CHECK-LABEL: entry:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    PUSH32 0x4E487B7100000000000000000000000000000000000000000000000000000000
; CHECK-NEXT:    PUSH1 0x80
; CHECK-NEXT:    MSTORE
; CHECK-NEXT:    PUSH1 0x80
; CHECK-NEXT:    MLOAD ; Reload Reuse
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 35408467139433450592217433187231851964531694900788300625387963629091585785856)
  unreachable
}

define void @test_spill() #2 {
; CHECK-LABEL: test_spill:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 0x80
; CHECK-NEXT:    MLOAD ; Reload Reuse
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 35408467139433450592217433187231851964531694900788300625387963629091585785856)
  unreachable
}

; Check that -1 constant is not spilled.
define void @test_not_spiller() #2 {
; CHECK-LABEL: test_not_spiller:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    NOT
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 -1)
  unreachable
}

; Check that small constants are not spilled.
define void @test_not_spilled2() #2 {
; CHECK-LABEL: test_not_spilled2:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH5 0x100000000
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 4294967296)
  unreachable
}

; Check that small constants are not spilled.
define void @test_not_spilled3() #2 {
; CHECK-LABEL: test_not_spilled3:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH5 0x100000000
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 4294967296)
  unreachable
}

attributes #1 = { nofree noreturn nounwind "evm-entry-function" }
attributes #2 = { nofree nounwind noreturn }
