; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=early-cse -S < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

declare i256 @llvm.evm.signextend(i256, i256)

define i256 @test_signextend1() {
; CHECK-LABEL: define i256 @test_signextend1() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 0, i256 255)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 0, i256 255)
  ret i256 %res
}

define i256 @test_signextend2() {
; CHECK-LABEL: define i256 @test_signextend2() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 1, i256 32767)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 1, i256 32767)
  ret i256 %res
}

define i256 @test_signextend3() {
; CHECK-LABEL: define i256 @test_signextend3() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 undef, i256 32767)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 undef, i256 32767)
  ret i256 %res
}

define i256 @test_signextend4() {
; CHECK-LABEL: define i256 @test_signextend4() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 1, i256 undef)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 1, i256 undef)
  ret i256 %res
}

define i256 @test_signextend5() {
; CHECK-LABEL: define i256 @test_signextend5() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 32, i256 undef)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 32, i256 undef)
  ret i256 %res
}

define i256 @test_signextend6() {
; CHECK-LABEL: define i256 @test_signextend6() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 0, i256 0)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 0, i256 0)
  ret i256 %res
}

define i256 @test_signextend7() {
; CHECK-LABEL: define i256 @test_signextend7() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 0, i256 1)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 0, i256 1)
  ret i256 %res
}

define i256 @test_signextend8() {
; CHECK-LABEL: define i256 @test_signextend8() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 0, i256 37670211480306196047687443673641227745170897112008692523754794019498533073987)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 0, i256 37670211480306196047687443673641227745170897112008692523754794019498533073987)
  ret i256 %res
}

define i256 @test_signextend9() {
; CHECK-LABEL: define i256 @test_signextend9() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 0, i256 -1)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 0, i256 -1)
  ret i256 %res
}

define i256 @test_signextend10() {
; CHECK-LABEL: define i256 @test_signextend10() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 1, i256 0)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 1, i256 0)
  ret i256 %res
}

define i256 @test_signextend11() {
; CHECK-LABEL: define i256 @test_signextend11() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 1, i256 1)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 1, i256 1)
  ret i256 %res
}

define i256 @test_signextend12() {
; CHECK-LABEL: define i256 @test_signextend12() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 1, i256 37670211480306196047687443673641227745170897112008692523754794019498533094467)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 1, i256 37670211480306196047687443673641227745170897112008692523754794019498533094467)
  ret i256 %res
}

define i256 @test_signextend13() {
; CHECK-LABEL: define i256 @test_signextend13() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 1, i256 -1)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 1, i256 -1)
  ret i256 %res
}

define i256 @test_signextend14() {
; CHECK-LABEL: define i256 @test_signextend14() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 17, i256 0)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 17, i256 0)
  ret i256 %res
}

define i256 @test_signextend15() {
; CHECK-LABEL: define i256 @test_signextend15() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 4, i256 1)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 4, i256 1)
  ret i256 %res
}

define i256 @test_signextend16() {
; CHECK-LABEL: define i256 @test_signextend16() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 22, i256 9111590707254702215554908033119796504552448929051039916)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 22, i256 9111590707254702215554908033119796504552448929051039916)
  ret i256 %res
}

define i256 @test_signextend17() {
; CHECK-LABEL: define i256 @test_signextend17() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 17, i256 25236770892255973364820642850062731514599596)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 17, i256 25236770892255973364820642850062731514599596)
  ret i256 %res
}

define i256 @test_signextend18() {
; CHECK-LABEL: define i256 @test_signextend18() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 22, i256 16774068411584146507346643168871342422646144539969050796)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 22, i256 16774068411584146507346643168871342422646144539969050796)
  ret i256 %res
}

define i256 @test_signextend19() {
; CHECK-LABEL: define i256 @test_signextend19() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 17, i256 93509753590725542020426220953279705230436762145237986916280948908)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 17, i256 93509753590725542020426220953279705230436762145237986916280948908)
  ret i256 %res
}

define i256 @test_signextend20() {
; CHECK-LABEL: define i256 @test_signextend20() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 25, i256 -1)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 25, i256 -1)
  ret i256 %res
}

define i256 @test_signextend21() {
; CHECK-LABEL: define i256 @test_signextend21() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 255, i256 0)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 255, i256 0)
  ret i256 %res
}

define i256 @test_signextend22() {
; CHECK-LABEL: define i256 @test_signextend22() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 255, i256 1)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 255, i256 1)
  ret i256 %res
}

define i256 @test_signextend23() {
; CHECK-LABEL: define i256 @test_signextend23() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 255, i256 -49173855447680950519990795082874703144781591387221730505838393986436314155965)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 255, i256 66618233789635244903580189925813204708488393278418833533619190021476815483971)
  ret i256 %res
}

define i256 @test_signextend24() {
; CHECK-LABEL: define i256 @test_signextend24() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 255, i256 -1)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 255, i256 -1)
  ret i256 %res
}

define i256 @test_signextend25() {
; CHECK-LABEL: define i256 @test_signextend25() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 256, i256 0)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 256, i256 0)
  ret i256 %res
}

define i256 @test_signextend26() {
; CHECK-LABEL: define i256 @test_signextend26() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 256, i256 37670211480306196047687443673641227745170897112008692523754794019498533073987)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 256, i256 37670211480306196047687443673641227745170897112008692523754794019498533073987)
  ret i256 %res
}

define i256 @test_signextend27() {
; CHECK-LABEL: define i256 @test_signextend27() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 256, i256 -1)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 256, i256 -1)
  ret i256 %res
}

define i256 @test_signextend28() {
; CHECK-LABEL: define i256 @test_signextend28() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 35242523534534534233424343343443, i256 1)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 35242523534534534233424343343443, i256 1)
  ret i256 %res
}

define i256 @test_signextend29() {
; CHECK-LABEL: define i256 @test_signextend29() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 35242523534534534233424343343443, i256 37670211480306196047687443673641227745170897112008692523754794019498533073987)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 35242523534534534233424343343443, i256 37670211480306196047687443673641227745170897112008692523754794019498533073987)
  ret i256 %res
}

define i256 @test_signextend30() {
; CHECK-LABEL: define i256 @test_signextend30() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 35242523534534534233424343343443, i256 -1)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 35242523534534534233424343343443, i256 -1)
  ret i256 %res
}

define i256 @test_signextend31() {
; CHECK-LABEL: define i256 @test_signextend31() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 -1, i256 0)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 -1, i256 0)
  ret i256 %res
}

define i256 @test_signextend32() {
; CHECK-LABEL: define i256 @test_signextend32() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 -1, i256 1)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 -1, i256 1)
  ret i256 %res
}

define i256 @test_signextend33() {
; CHECK-LABEL: define i256 @test_signextend33() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 -1, i256 37670211480306196047687443673641227745170897112008692523754794019498533073987)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 -1, i256 37670211480306196047687443673641227745170897112008692523754794019498533073987)
  ret i256 %res
}

define i256 @test_signextend34() {
; CHECK-LABEL: define i256 @test_signextend34() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 -1, i256 -1)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 -1, i256 -1)
  ret i256 %res
}

define i256 @test_signextend35() {
; CHECK-LABEL: define i256 @test_signextend35() {
; CHECK-NEXT:    [[RES:%.*]] = call i256 @llvm.evm.signextend(i256 0, i256 33023)
; CHECK-NEXT:    ret i256 [[RES]]
;

  %res = call i256 @llvm.evm.signextend(i256 0, i256 33023)
  ret i256 %res
}
