; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

; CHECK-NOT: JUMPI

; Function for cond ? X : 0 (false value is 0)
define i256 @sel_x_or_0(i1 %cond, i256 %x) {
; CHECK-LABEL: sel_x_or_0:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 0x1
; CHECK-NEXT:    AND
; CHECK-NEXT:    MUL
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP
%val = select i1 %cond, i256 %x, i256 0
ret i256 %val
}

; Function for cond ? 0 : Y (true value is 0)
define i256 @sel_0_or_y(i1 %cond, i256 %y) {
; CHECK-LABEL: sel_0_or_y:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 0x1
; CHECK-NEXT:    AND
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    MUL
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP
%val = select i1 %cond, i256 0, i256 %y
ret i256 %val
}

; Function for cond ? X : 1 (false value is 1)
define i256 @sel_x_or_1(i1 %cond, i256 %x) {
; CHECK-LABEL: sel_x_or_1:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 0x1
; CHECK-NEXT:    AND
; CHECK-NEXT:    DUP1
; CHECK-NEXT:    SWAP2
; CHECK-NEXT:    MUL
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    ADD
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP
%val = select i1 %cond, i256 %x, i256 1
ret i256 %val
}

; Function for cond ? 1 : Y (true value is 1)
define i256 @sel_1_or_y(i1 %cond, i256 %y) {
; CHECK-LABEL: sel_1_or_y:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    POP
; CHECK-NEXT:    PUSH1 0x1
; CHECK-NEXT:    AND
; CHECK-NEXT:    DUP1
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    ADD
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP
%val = select i1 %cond, i256 1, i256 %y
ret i256 %val
}
