; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s | FileCheck %s
target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

@data1 = private unnamed_addr addrspace(4) constant [5 x i8] c"xQm7A"
@data2 = private unnamed_addr addrspace(4) constant [5 x i8] c"T2bLp"
@data3 = private unnamed_addr addrspace(4) constant [5 x i8] c"rZ8Wd"
@data4 = private unnamed_addr addrspace(4) constant [5 x i8] c"NfC3y"
@data5 = private unnamed_addr addrspace(4) constant [5 x i8] c"qHs0J"

declare void @llvm.evm.revert.sptr(ptr addrspace(1) readonly, i256, ptr addrspace(5), ptr addrspace(6))
declare void @llvm.memcpy.p1.p4.i256(ptr addrspace(1) noalias nocapture writeonly, ptr addrspace(4) noalias nocapture readonly, i256, i1 immarg)

define void @test() noreturn {
; CHECK-LABEL: test:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 0x5
; CHECK-NEXT:    PUSH4 @code_data_section
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    CODECOPY
; CHECK-NEXT:    PUSH1 0x5
; CHECK-NEXT:    PUSH4 @code_data_section+5
; CHECK-NEXT:    PUSH1 0x8
; CHECK-NEXT:    CODECOPY
; CHECK-NEXT:    PUSH1 0x5
; CHECK-NEXT:    PUSH4 @code_data_section+10
; CHECK-NEXT:    PUSH1 0x10
; CHECK-NEXT:    CODECOPY
; CHECK-NEXT:    PUSH1 0x5
; CHECK-NEXT:    PUSH4 @code_data_section+15
; CHECK-NEXT:    PUSH1 0x18
; CHECK-NEXT:    CODECOPY
; CHECK-NEXT:    PUSH1 0x5
; CHECK-NEXT:    PUSH4 @code_data_section+20
; CHECK-NEXT:    PUSH1 0x20
; CHECK-NEXT:    CODECOPY
; CHECK-NEXT:    PUSH1 0x80
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    REVERT
; CHECK:         INVALID
; CHECK-LABEL:  code_data_section:
; CHECK-NEXT:    .byte 0x78, 0x51, 0x6d, 0x37
; CHECK-NEXT:    .byte 0x41, 0x54, 0x32, 0x62
; CHECK-NEXT:    .byte 0x4c, 0x70, 0x72, 0x5a
; CHECK-NEXT:    .byte 0x38, 0x57, 0x64, 0x4e
; CHECK-NEXT:    .byte 0x66, 0x43, 0x33, 0x79
; CHECK-NEXT:    .byte 0x71, 0x48, 0x73, 0x30
; CHECK-NEXT:    .byte 0x4a

  call void @llvm.memcpy.p1.p4.i256(ptr addrspace(1) null, ptr addrspace(4) @data1, i256 5, i1 false)
  %dst2 = inttoptr i256 8 to ptr addrspace(1)
  call void @llvm.memcpy.p1.p4.i256(ptr addrspace(1) %dst2, ptr addrspace(4) @data2, i256 5, i1 false)
  %dst3 = inttoptr i256 16 to ptr addrspace(1)
  call void @llvm.memcpy.p1.p4.i256(ptr addrspace(1) %dst3, ptr addrspace(4) @data3, i256 5, i1 false)
  %dst4 = inttoptr i256 24 to ptr addrspace(1)
  call void @llvm.memcpy.p1.p4.i256(ptr addrspace(1) %dst4, ptr addrspace(4) @data4, i256 5, i1 false)
  %dst5 = inttoptr i256 32 to ptr addrspace(1)
  call void @llvm.memcpy.p1.p4.i256(ptr addrspace(1) %dst5, ptr addrspace(4) @data5, i256 5, i1 false)
  call void @llvm.evm.revert.sptr(ptr addrspace(1) null, i256 128, ptr addrspace(5) null, ptr addrspace(6) null)
  unreachable
}
