; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

define i256 @udivrrr(i256 %rs1, i256 %rs2) nounwind {
; CHECK-LABEL: udivrrr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    DIV
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = udiv i256 %rs1, %rs2
  ret i256 %res
}

define i256 @sdivrrr(i256 %rs1, i256 %rs2) nounwind {
; CHECK-LABEL: sdivrrr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SDIV
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = sdiv i256 %rs1, %rs2
  ret i256 %res
}

define i256 @sdivrri(i256 %rs1) nounwind {
; CHECK-LABEL: sdivrri:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    POP
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = sdiv i256 %rs1, 0
  ret i256 %res
}
