; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=instcombine -S < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

declare i256 @llvm.smin.i256(i256, i256)

define i256 @test(i256 %x, i256 %y, i256 %z) {
; CHECK-LABEL: define i256 @test(
; CHECK-SAME: i256 [[X:%.*]], i256 [[Y:%.*]], i256 [[Z:%.*]]) {
; CHECK-NEXT:    [[Y2:%.*]] = shl nuw i256 1, [[Y]]
; CHECK-NEXT:    [[Z2:%.*]] = shl nuw i256 1, [[Z]]
; CHECK-NEXT:    [[M:%.*]] = call i256 @llvm.smin.i256(i256 [[Y2]], i256 [[Z2]])
; CHECK-NEXT:    [[D1:%.*]] = udiv i256 [[X]], [[M]]
; CHECK-NEXT:    ret i256 [[D1]]
;
  %y2 = shl i256 1, %y
  %z2 = shl i256 1, %z
  %m = call i256 @llvm.smin.i256(i256 %y2, i256 %z2)
  %d = udiv i256 %x, %m
  ret i256 %d
}
