; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -O3 --evm-const-unfolding-size-gain-threshold=0 --evm-const-unfolding-inst-num-limit=10  < %s | FileCheck %s
target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm-unknown-unknown"

declare void @llvm.evm.return(ptr addrspace(1), i256) noreturn

; Verifies that constant unfolding occurs in non-OptForSize mode when limits
; are overridden through options.


; 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000
define void @test8() #1 {
; CHECK-LABEL: test8:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH16 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
; CHECK-NEXT:    PUSH1 0x80
; CHECK-NEXT:    SHL
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 57896044618658097711785492504343953926294709965899343556265417396524796608512)
  unreachable
}

; 0x00000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
define void @test2() #1 {
; CHECK-LABEL: test2:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    NOT
; CHECK-NEXT:    PUSH1 0x54
; CHECK-NEXT:    SHR
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 5986310706507378352962293074805895248510699696029695)
  unreachable
}

attributes #1 = { nofree nounwind noreturn }
