; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -O3 < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

declare void @llvm.evm.return(ptr addrspace(1), i256)

define void @__entry() noreturn {
; CHECK-LABEL: __entry:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    MLOAD
; CHECK-NEXT:    DUP1
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    PUSH4 @.BB0_2
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:  .BB0_2: ; %bb1
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    POP
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    MSTORE
; CHECK-NEXT:    PUSH1 0x20
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    RETURN
entry:
  %load = load i256, ptr addrspace(1) null, align 64
  %cmp = icmp eq i256 %load, 0
  br i1 %cmp, label %bb2, label %bb1

bb1:
  br label %bb2

bb2:
  %phi = phi i256 [ 0, %entry ], [ %load, %bb1 ]
  store i256 %phi, ptr addrspace(1) null, align 64
  tail call void @llvm.evm.return(ptr addrspace(1) null, i256 32)
  unreachable
}
