; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -O3 < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

declare i256 @bar()

define i256 @test(i256 %a, i256 %b) {
; CHECK-LABEL: test:
; CHECK:       ; %bb.0: ; %bb1
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    AND
; CHECK-NEXT:    PUSH4 @.BB0_3
; CHECK-NEXT:    JUMPI
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP
; CHECK-NEXT:  .BB0_3: ; %bb4
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH4 @.FUNC_RET0
; CHECK-NEXT:    PUSH4 @bar
; CHECK-NEXT:    JUMP
; CHECK-NEXT:  .FUNC_RET0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP
bb1:
  %0 = icmp eq i256 %a, 0
  %1 = icmp eq i256 %b, 0
  %or = or i1 %0, %1
  br i1 %or, label %bb3, label %bb4

bb3:
  ret i256 0

bb4:
  %2 = call i256 @bar()
  ret i256 %2
}
