; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

define i1 @simplify_setcc(ptr addrspace(1) %glob) {
; CHECK-LABEL: simplify_setcc:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 0x2
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    MLOAD
; CHECK-NEXT:    AND
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP
  %val = load i256, ptr addrspace(1) %glob, align 32
  %val.and = and i256 %val, 2
  %cmp = icmp eq i256 %val.and, 0
  ret i1 %cmp
}
