; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

define i256 @andrrr(i256 %rs1, i256 %rs2) nounwind {
; CHECK-LABEL: andrrr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    AND
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = and i256 %rs1, %rs2
  ret i256 %res
}

define i256 @orrrr(i256 %rs1, i256 %rs2) nounwind {
; CHECK-LABEL: orrrr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    OR
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = or i256 %rs1, %rs2
  ret i256 %res
}

define i256 @xorrrr(i256 %rs1, i256 %rs2) nounwind {
; CHECK-LABEL: xorrrr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    XOR
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = xor i256 %rs1, %rs2
  ret i256 %res
}

define i256 @notrrr(i256 %rs1, i256 %rs2) nounwind {
; CHECK-LABEL: notrrr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    POP
; CHECK-NEXT:    NOT
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = xor i256 %rs1, -1
  ret i256 %res
}
