; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

define i256 @mload(ptr addrspace(2) %offset) nounwind {
; CHECK-LABEL: mload:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    CALLDATALOAD
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %val = load i256, ptr addrspace(2) %offset, align 32
  ret i256 %val
}
