; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

define void @mstore8(ptr addrspace(1) %offset, i256 %val) nounwind {
; CHECK-LABEL: mstore8:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    MSTORE8
; CHECK-NEXT:    JUMP

  call void @llvm.evm.mstore8(ptr addrspace(1) %offset, i256 %val)
  ret void
}

define void @mstore(ptr addrspace(1) %offset, i256 %val) nounwind {
; CHECK-LABEL: mstore:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    MSTORE
; CHECK-NEXT:    JUMP

  store i256 %val, ptr addrspace(1) %offset, align 32
  ret void
}

define i256 @mload(ptr addrspace(1) %offset) nounwind {
; CHECK-LABEL: mload:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    MLOAD
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %val = load i256, ptr addrspace(1) %offset, align 32
  ret i256 %val
}

declare void @llvm.evm.mstore8(ptr addrspace(1), i256)
