; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

define i256 @umodrrr(i256 %rs1, i256 %rs2) nounwind {
; CHECK-LABEL: umodrrr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    MOD
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = urem i256 %rs1, %rs2
  ret i256 %res
}

define i256 @smodrrr(i256 %rs1, i256 %rs2) nounwind {
; CHECK-LABEL: smodrrr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SMOD
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = srem i256 %rs1, %rs2
  ret i256 %res
}

define i256 @smodrri(i256 %rs1) nounwind {
; CHECK-LABEL: smodrri:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    POP
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = srem i256 %rs1, 0
  ret i256 %res
}
