; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

define i256 @mulrrr(i256 %rs1, i256 %rs2) nounwind {
; CHECK-LABEL: mulrrr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    MUL
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = mul i256 %rs1, %rs2
  ret i256 %res
}

define i256 @mulrri(i256 %rs1) nounwind {
; CHECK-LABEL: mulrri:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH3 0x7A120
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    SUB
; CHECK-NEXT:    MUL
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = mul i256 %rs1, -500000
  ret i256 %res
}
