; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc  < %s | FileCheck %s
target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm-unknown-unknown"

define i1 @test_eq(i256 %x) {
; CHECK-LABEL: test_eq:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP
  %cmp = icmp eq i256 %x, 0
  ret i1 %cmp
}

define i1 @test_ne(i256 %x) {
; CHECK-LABEL: test_ne:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    ISZERO
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP
  %cmp = icmp ne i256 %x, 0
  ret i1 %cmp
}
