; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

define i256 @sexti1(i1 %rs1) nounwind {
; CHECK-LABEL: sexti1:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 1
; CHECK-NEXT:    AND
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    SUB
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = sext i1 %rs1 to i256
  ret i256 %res
}

define i256 @sexti8(i8 %rs1) nounwind {
; CHECK-LABEL: sexti8:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    SIGNEXTEND
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = sext i8 %rs1 to i256
  ret i256 %res
}

define i256 @sexti16(i16 %rs1) nounwind {
; CHECK-LABEL: sexti16:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 1
; CHECK-NEXT:    SIGNEXTEND
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = sext i16 %rs1 to i256
  ret i256 %res
}

define i256 @sexti32(i32 %rs1) nounwind {
; CHECK-LABEL: sexti32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 3
; CHECK-NEXT:    SIGNEXTEND
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = sext i32 %rs1 to i256
  ret i256 %res
}

define i256 @sexti64(i64 %rs1) nounwind {
; CHECK-LABEL: sexti64:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 7
; CHECK-NEXT:    SIGNEXTEND
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = sext i64 %rs1 to i256
  ret i256 %res
}

define i256 @sexti128(i128 %rs1) nounwind {
; CHECK-LABEL: sexti128:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 15
; CHECK-NEXT:    SIGNEXTEND
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = sext i128 %rs1 to i256
  ret i256 %res
}

; Check that 'sext' also gets lowered for types not declared in MVT.
define i256 @sexti40(i40 %rs1) nounwind {
; CHECK-LABEL: sexti40:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 216
; CHECK-NEXT:    SHL
; CHECK-NEXT:    PUSH1 216
; CHECK-NEXT:    SAR
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = sext i40 %rs1 to i256
  ret i256 %res
}
