; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

define i256 @shl(i256 %rs1, i256 %rs2) nounwind {
; CHECK-LABEL: shl:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    SHL
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = shl i256 %rs1, %rs2
  ret i256 %res
}

define i256 @shr(i256 %rs1, i256 %rs2) nounwind {
; CHECK-LABEL: shr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    SHR
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = lshr i256 %rs1, %rs2
  ret i256 %res
}

define i256 @sar(i256 %rs1, i256 %rs2) nounwind {
; CHECK-LABEL: sar:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    SAR
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = ashr i256 %rs1, %rs2
  ret i256 %res
}
