; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

declare void @llvm.evm.log0(ptr addrspace(1), i256)

define void @test() noreturn {
; CHECK-LABEL: test:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH5 956397711105
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    MSTORE
; CHECK-NEXT:    PUSH1 32
; CHECK-NEXT:    PUSH0
; CHECK-NEXT:    LOG0
; CHECK-NEXT:    STOP
entry:
  store i256 956397711105, ptr addrspace(1) null, align 4294967296
  tail call void @llvm.evm.log0(ptr addrspace(1) noalias nocapture nofree noundef nonnull align 32 null, i256 32)
  unreachable
}
