; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

define void @sstore(ptr addrspace(5) %key, i256 %val) nounwind {
; CHECK-LABEL: sstore:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SSTORE
; CHECK-NEXT:    JUMP

  store i256 %val, ptr addrspace(5) %key, align 32
  ret void
}

define i256 @sload(ptr addrspace(5) %key) nounwind {
; CHECK-LABEL: sload:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SLOAD
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %val = load i256, ptr addrspace(5) %key, align 32
  ret i256 %val
}
