; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

define i256 @subrrr(i256 %rs1, i256 %rs2) nounwind {
; CHECK-LABEL: subrrr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SUB
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = sub i256 %rs1, %rs2
  ret i256 %res
}

define i256 @addrri(i256 %rs1) nounwind {
; CHECK-LABEL: addrri:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    PUSH1 0x3
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    SUB
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %res = add i256 %rs1, -3
  ret i256 %res
}
