; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

define void @storei8(i8 %val, ptr addrspace(1) %glob) nounwind {
; CHECK-LABEL: storei8:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    MSTORE8
; CHECK-NEXT:    JUMP

  store i8 %val, ptr addrspace(1) %glob
  ret void
}

define void @storei32(i32 %val, ptr addrspace(1) %glob) nounwind {
; CHECK-LABEL: storei32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    DUP2
; CHECK-NEXT:    MLOAD
; CHECK-NEXT:    PUSH1 0x20
; CHECK-NEXT:    SHR
; CHECK-NEXT:    PUSH1 0x20
; CHECK-NEXT:    SHL
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    PUSH1 0xE0
; CHECK-NEXT:    SHL
; CHECK-NEXT:    OR
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    MSTORE
; CHECK-NEXT:    JUMP

  store i32 %val, ptr addrspace(1) %glob
  ret void
}
