; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s | FileCheck %s

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm"

define void @tstore(ptr addrspace(6) %key, i256 %val) nounwind {
; CHECK-LABEL: tstore:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    TSTORE
; CHECK-NEXT:    JUMP

  store i256 %val, ptr addrspace(6) %key, align 32
  ret void
}

define i256 @tload(ptr addrspace(6) %key) nounwind {
; CHECK-LABEL: tload:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    TLOAD
; CHECK-NEXT:    SWAP1
; CHECK-NEXT:    JUMP

  %val = load i256, ptr addrspace(6) %key, align 32
  ret i256 %val
}
