; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc --mtriple=evm %s -o - | FileCheck %s

; CHECK-NOT: .note.GNU-stack

target datalayout = "E-p:256:256-i256:256:256-S256-a:256:256"
target triple = "evm-unknown-unknown"

declare void @llvm.evm.return(ptr addrspace(1), i256)

define void @foo() {
; CHECK-LABEL: foo:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    JUMPDEST
; CHECK-NEXT:    POP
; CHECK-NEXT:    PUSH4 0xFFFFFFFF
; CHECK-NEXT:    PUSH1 0xE0
; CHECK-NEXT:    SHL
; CHECK-NEXT:    PUSH1 0x40
; CHECK-NEXT:    RETURN
  tail call void @llvm.evm.return( ptr addrspace(1) inttoptr (i256 64 to ptr addrspace(1)), i256 -26959946667150639794667015087019630673637144422540572481103610249216)
  unreachable
}
