name: Forge benchmarks

on:
  workflow_dispatch:
    inputs:
      solx_candidate_branch:
        description: 'Solidity candidate branch to use. If empty, the current branch will be used.'
        required: false
        default: ''
      solx_reference_branch:
        description: 'Solidity reference branch to use. If empty, the current branch will be used.'
        required: false
        default: ''
      compiler_llvm_candidate_branch:
        description: 'LLVM candidate branch to use. If empty, the current branch will be used.'
        required: false
        default: ''
      compiler_llvm_reference_branch:
        description: 'LLVM reference branch to use. If empty, the current branch will be used.'
        required: false
        default: ''
  pull_request:

jobs:
  forge-benchmarks:
    uses: matter-labs/era-compiler-ci/.github/workflows/forge-benchmarks.yaml@aba-ref-can-rust-sum
    secrets: inherit
    with:
      upload-reports: ${{ github.event_name == 'pull_request' }}
      print-markdown-tables: 'false' # do not print markdown tables to PRs
      solx_candidate_branch: ${{ inputs.solx_candidate_branch || 'main' }}
      solx_reference_branch: ${{ inputs.solx_reference_branch || 'main' }}
      compiler_llvm_candidate_branch: ${{ inputs.compiler_llvm_candidate_branch || github.head_ref }}
      compiler_llvm_reference_branch: ${{ inputs.compiler_llvm_reference_branch || github.event.pull_request.base.ref || github.event.repository.default_branch }}
      compiler-llvm-repo: ${{ github.event.pull_request.head.repo.full_name || 'matter-labs/era-compiler-llvm' }} # required to properly test forks
