name: Build LLVM binaries

on:
  pull_request:
  schedule:
    - cron: '0 0 1 * *' # every month to regenerate ccache
  workflow_dispatch:
    inputs:
      ref:
        description: "Git REF to use for the build"
        required: false
        type: string
      enable_macos_amd64:
        description: "Enable MacOS amd64?"
        required: false
        type: boolean
        default: true
      enable_macos_arm64:
        description: "Enable MacOS arm64?"
        required: false
        type: boolean
        default: true
      enable_linux_amd64:
        description: "Enable Linux amd64?"
        required: false
        type: boolean
        default: true
      enable_linux_arm64:
        description: "Enable Linux arm64?"
        required: false
        type: boolean
        default: true
      enable_windows_amd64:
        description: "Enable Windows amd64?"
        required: false
        type: boolean
        default: true


jobs:

  integration-tests:
    uses: matter-labs/era-compiler-ci/.github/workflows/integration-tests.yaml@aba-multiplatform-integration-tests
    secrets: inherit
    with:
      compiler-tester-ref: 'main'
      llvm-ref: ${{ inputs.ref || github.head_ref }}
      ccache-key-type: 'static'
      compiler-llvm-repo: ${{ github.event.repository.full_name }}
      enable-linux-amd64: ${{ inputs.enable_linux_amd64 || true }}
      enable-macos-amd64: ${{ inputs.enable_macos_amd64 || true }}
      enable-macos-arm64: ${{ inputs.enable_macos_arm64 || true }}
      enable-linux-arm64: ${{ inputs.enable_linux_arm64 || false }} # not supported yet, compiler-tester issue with vyper linux arm64 binaries
      enable-windows-amd64: ${{ inputs.enable_windows_amd64 || false }} # not supported, long paths issue
